### ISSUE TITLE
Create Developer Guide

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#10]
Write a new windows guide and make cross-compiled binaries.

**Comment by DavidVorick** [comment]
Are you planning on writing a guide so people can develop from Windows?

**Comment by Mingling94** [comment]
I'm planning to develop from Windows. Seve asked me to make this an issue to remind him to do this

**Comment by DavidVorick** [comment]
Our attempts in the past to get people developing in go from Windows have been unsuccessful. If you won't be working with the go code, you might not run into the same issues.

It should be possible to develop in go from Windows, but we just haven't been able to make it happen. You might be the person to figure it out, or it might just be easier to install a VM. Seve probably knows better than I do about this.

**Comment by lukechampine** [comment]
Worth noting that the problems we encountered were primarily due to cgo. Developing a pure-Go project on Windows would be fairly straightforward.

**Comment by Mingling94** [comment]
So that guide was never made. I'm closing this issue for two reasons:

1. easier to dual-boot or get a linux VM going than to get go working on Windows
2. the release binaries available that prevents the need for a Sia-UI Windows dev to use golang.
