### ISSUE TITLE
Window size not preserved

### ISSUE THREAD

**Issue by snakes-r-us** [NebulousLabs/Sia-UI#101]
Currently the main window size is not preserved when the client gets shut down and restarted. Instead it will start up near-full screen, regardless of its previous setting.

Consider restoring the window size on startup as it was last set by the user.

**Comment by Mingling94** [comment]
Two values to be placed (and checked for upon startup) in the config.json :)

**Comment by DavidVorick** [comment]
I would like to note that the config.json is having some time of trouble where it is being replaced with 'undefined' from time to time.

**Comment by Mingling94** [comment]
Fixed via #105
