### ISSUE TITLE
Deadlocking?

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#103]
I'm not sure what the problem is, but it seems that siad becomes unresponsive after a few minutes when it's being run by the UI.

It doesn't seem to be a problem if I run my own siad in the background first.

**Comment by DavidVorick** [comment]
It seems that the stderr buffer is filling up and that's causing things to freeze. We got rid of the log file, which means that all logging messages from the api were just going to stderr.  The UI triggers so many log messages though that the buffer was filling up and dying in only like 30 seconds.

We fixed this by sending all logging messages to the cross-platform version of /dev/null.

My guess is that there's still a problem here, and that all Sia-UI windows are destined for death after running long enough. This is no longer an immediate concern though.

**Comment by lukechampine** [comment]
Looks like we can tell node to pipe stderr to /dev/null: https://nodejs.org/api/child_process.html#child_process_options_stdio

Alternatively we could pipe it to stdout. It doesn't matter much at this point since we aren't doing anything with the output.
