### ISSUE TITLE
Ascii Filesharing

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#105]
I'd really like to see this available for the release this week. Hopefully it's rather simple to implement.

In the renter, each file should have a 'share' button next to it. That share button will call /renter/files/shareascii and a popup will appear with the ascii characters (~4k-8k of them).

There should be a 'load files' button somewhere. Clicking it pops up a text box where you can paste the 4k-8k ascii characters. These characters will be used to call /renter/files/loadascii

This will enable a user to upload a file, get the ascii, share the ascii, and then the person they share it with can download the file that they uploaded.

**Comment by seveibar** [comment]
on it
