### ISSUE TITLE
Incorrect version reporting

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#108]
On the about page, the siad version is taken from the `/update` API response. However, this is not the current version, but the most recent version (i.e. the version you would update to). The relevant code is in controller.js.

There is no API call to get the current version, but one will probably be added soon.

**Comment by DavidVorick** [comment]
do you understand it well enough to just statically replace the version number with "0.3.1" for now?

**Comment by lukechampine** [comment]
Well, once we push out the next siad release it'll be updated correctly. Hard-coding it isn't any better or worse.

**Comment by DavidVorick** [comment]
ok
