### ISSUE TITLE
which one of these downloads works on Mac OS X?

### ISSUE THREAD

**Issue by prophet10x** [NebulousLabs/Sia-UI#109]
sorry i couldn't figure out from the long file names...

just something so simple as direct downloads on your website would probably increase your adoption 10 fold... just from friendly advice from someone that wanted to pay your network some money...

**Comment by Mingling94** [comment]
https://github.com/NebulousLabs/Sia-UI/releases/tag/v0.4.6-beta
Have you tried the darwin.zip?

**Comment by lukechampine** [comment]
OS X is commonly referred to as "darwin" in the developer community. Perhaps we should be more clear about this. Direct download links sound like a good idea regardless.

**Comment by Mingling94** [comment]
Yeah, I guess the sia.tech page should link to the actual zips with OS-icon links, or even based on OS detection and avoid linking to Github as much as possible.

The point of the page is to appeal to non-developer audiences as much as possible so I think we should do the above. @DavidVorick what do you think?

**Comment by prophet10x** [comment]
ah right forgot about the use of darwin, thanks for the quick responce

Thanks,

Dominik Zynis
twitter.com/chloregy
Skype: dominik.zynis
USA: +1-415-800-4155
EU: +34-615-402-046
dominik.zynis@gmail.com
