### ISSUE TITLE
Prettify Siacoin numbers in UI

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia-UI#110]
Display Siacoin in language sensitive representations, e.g. instead of 1829438.32 show 1,829,438.32, with `parseFloat(amount, 10).toLocaleString();`.

A second, related, issue: Functions used to display Siacoin in UI include `formatSiacoin()` (Overview) and `convertSiacoin()` (Wallet, Files & Hosting). So, there are 4 function instances that pretty much do the same. Is there a logical place for a combined function upstream of the `/plugin` directory, or do these functions belong only in the plugin code?

**Comment by Mingling94** [comment]
They're in plugin code to reduce the amount of IPC that we use. The goal of designing plugins was so that developing them was as similar to web-dev as possible.

It's a small amount of duplicated code but we're open to suggestions

**Comment by DavidVorick** [comment]
Maybe we can make a siacoin node module that the plugins can import?

**Comment by Mingling94** [comment]
^ Along the same lines I want to make a siad node module to wrap api calls. Basically it's what daemonManager currently does, though I want it to be available for other node projects to use. Making a siacoin node module for the things that generally go in the plugins' `helper.js` would be a good practice for making node modules in general

**Comment by DavidVorick** [comment]
makes sense to me

**Comment by DavidVorick** [comment]
has this been resolved with the new node package, or does it still need to be implemented?

**Comment by Mingling94** [comment]
Yeah this can be added functionality in the https://github.com/NebulousLabs/Nodejs-Sia repo. Some basic convertToSiacoin(), convertToHastings, and formatToSiacoin() functions would be a good utility.

**Comment by DavidVorick** [comment]
Ok. The explorer has a function called humanReadableSiacoins(), and humanReadableByteCount() or something to that effect, which will convert it to different units depending on what produces the cleanest number.

Maybe something similar should be added to the nodejs, instead of having a different function for each Siacoin() and Hastings() etc.

**Comment by lukechampine** [comment]
@johnathanhowell @droghio, is there a `toLocaleString` equivalent for `BigNumber` values? Even if not, we should make an effort to use `toLocaleString` where it makes sense.

**Comment by DavidVorick** [comment]
Can we close this? Don't we already have functions in the UI for converting to and from the various units in Sia?
