### ISSUE TITLE
Live wallet balance updating

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#112]
Would be nice if your wallet balance updated in real-time. Currently you have to reload the page.

Ugh, I wish we could do this stuff via "pushing" updates from the server instead of polling.

**Comment by Mingling94** [comment]
@lukechampine is that what websockets would do?

**Comment by lukechampine** [comment]
To my knowledge, yes. For now we aren't planning on using them though.

**Comment by DavidVorick** [comment]
websockets would be nice for the miner too, instead of using libcurl we'd just have a socket open that we could pour data down.

Removing libcurl would solve some of the problems windows users have been having.

**Comment by Mingling94** [comment]
To then, without web sockets or a dispatching setup from the server, this could only be solved with a partial solution through #96?

**Comment by lukechampine** [comment]
#96 is not relevant to this issue. It's about synchronizing siad with other peers, not synchronizing siad with Sia-UI.

We already have polling functions (`update`) that serve this purpose. We just need to adapt them to update the balance.
