### ISSUE TITLE
Destination path too long

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#116]
From a user:

```
I downloaded the "win32" wallet and im promted with an error when i try to unpack "win32".

"Destination path too long"
node_modules
lib
test

The wallet starts instantly but some tabs in the wallet do not work.
```

I think this because our release folder uses some absurdly long names. Perhaps we can address this some way?

**Comment by lukechampine** [comment]
ugh yeah, this is a known issue with ~~atom shell~~ electron apps. On windows, you need to unzip them in C:\, otherwise the path is too long. Would be a good idea to mention this somewhere, maybe the Troubleshooting section of the README.

**Comment by DavidVorick** [comment]
:'(

https://github.com/atom/atom/pull/5175

It looks like you can use up to 55 characters in your path, so you've got wiggle room beyond top-level.

That's still awful though.

**Comment by DavidVorick** [comment]
Maybe the best solution is to have an installer for Windows users

**Comment by lukechampine** [comment]
agreed, we should make the Windows experience as easy as possible since that's probably where most of our users will be.

**Comment by lukechampine** [comment]
this is actually a packaging problem, not something inherent to this repo. So this is "fixed" assuming we do our packaging properly in the future.
