### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#120]
Many of our error messages are too long, and don't fit in the notification window. We need some way of displaying or capturing these errors in full. They are important for debugging purposes.

**Comment by DavidVorick** [comment]
logging? Errors plugin?

Might not be necessary to expose them to the user, but maybe there should be some data structure that holds the whole notification history

**Comment by lukechampine** [comment]
I think logging to a file would be best. When a user gets an error we want to be able to point them to a specific record of the full error message, so that we can properly diagnose it.

**Comment by DavidVorick** [comment]
do we want to log all notifications, or only error notifications?

**Comment by Mingling94** [comment]
Definitely just error notifications. There's only so many times one can read "Sia client up to date!"

**Comment by DavidVorick** [comment]
Maybe a sign that we don't need to display a notification about being up to date.

**Comment by lukechampine** [comment]
There's not much value in "Address created!" or "Wallet unlocked!" either. Unless you want to trace every action of the user, so as to replay precisely what they did. But logging just error messages seems pretty sane to me.

**Comment by DavidVorick** [comment]
yeah that makes sense
