### ISSUE TITLE
Host view

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#122]
The host view should show the number of files/contracts and the amount of storage in use. In fact, I think these should be the primary items in the host view. The hosting settings can be featured less prominently, since you change them only infrequently.

**Comment by DavidVorick** [comment]
These variables I believe all already exist inside of the Host object, you would really only need to change the HostInfo struct.

**Comment by lukechampine** [comment]
they're definitely available to the API because siac reports them with `siac host`. The UI just hasn't ever made use of them.

**Comment by Mingling94** [comment]
So should files/contract still be shown?

And should this be in another capsule called "Hosting Statistics" above/below "Configure Hosting" since the header's getting overpopulated?

**Comment by DavidVorick** [comment]
We really just need to redesign the hosting page from scratch.

**Comment by DavidVorick** [comment]
it's fine for the immediate future though.
