### ISSUE TITLE
Transactions in the UI

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#124]
Tried to load all of the transactions, a CPU core got pegged for about 10 minutes, app wouldn't close. Finally resolved after maybe 25 minutes.

Is there a polynomial-time algorithm that's happening? It was fine a few days ago, but I've added transactions since then. Doesn't seem like an infinite loop because it did eventually finish. Either way, the transactions function of our UI is basically unusable. Pretty much the same with regards to siac.

**Comment by pmknutsen** [comment]
As I recall from last time this was encountered, the problem sits deep. If
no fix is found, siac should return paginated results instead of the entire
wallet history, e.g.

Return the last 100 transactions:
GET `/wallet/transactions?size=100&from=100`

and the next 100 transactions:
GET `/wallet/transactions?size=100&from=200`

or, alternatively:

Return the last 100 transactions:
GET `/wallet/transactions?start=100&end=0`

and the next 100 transactions:
GET `/wallet/transactions?start=200&end=100`

**Comment by pmknutsen** [comment]
The same applies to addresses by the way. With 10,000+ addresses in my wallet the list takes a couple of seconds to display.

**Comment by DavidVorick** [comment]
10,000+... we should improve that. I'm guessing most of your addresses come from uploading files. At some point in the near future (maybe 3-6 weeks?) we're going to be switching up the way that host contracts are formed, that should heavily cut back on the number of addresses. But we should probably have pagination anyway.

**Comment by pmknutsen** [comment]
![screenshot from 2015-11-06 08 21 06](https://cloud.githubusercontent.com/assets/1565499/11002059/64d7fd0a-845f-11e5-9036-0a205a87981a.png)

**Comment by Mingling94** [comment]
For testing purposes, around what number were your problematic amounts of transactions?

**Comment by pmknutsen** [comment]
Not sure, but it scales. I would guess thousands of transactions should result in a very noticeable lag.

**Comment by Mingling94** [comment]
Are there examples of apps, websites, or anything DOM-like where creating thousands of elements doesn't produce some lag?

I've made the lag (at least for address creation, doing transactions next) somewhat non-blocking in #134 so one can still click around and see GUI response.

**Comment by DavidVorick** [comment]
@Mingling94 you probably shouldn't be creating thousands of dom elements all at once. Even if you are still fetching thousands of transactions from a single api call, you only need to build O(25) dom elements at a time, and then have a 'next page' button that will generate and delete dom elements _after_ you click the button.

**Comment by Mingling94** [comment]
Solved by #140
