### ISSUE TITLE
build unknown

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#129]
Why is the build unknown? It looks to me like the build is passing.

**Comment by Mingling94** [comment]
Good question, I'm not sure what these odd git commands have to do with it:
![job -37 2 - nebulouslabs-sia-ui - travis ci - google chrome_036](https://cloud.githubusercontent.com/assets/4606838/11148499/0ed73894-89eb-11e5-8a30-30838296299a.png)

**Comment by DavidVorick** [comment]
that's weird, looks like a bug with travis.

**Comment by lukechampine** [comment]
nah that's my bad, happened when I hit the "restart build" button on travis. I was hoping it would update the status

**Comment by Mingling94** [comment]
It actually does seem to be with Travis though https://github.com/travis-ci/travis-ci/issues/3996

**Comment by Mingling94** [comment]
It probably has to do with this:
![workspace 2_038](https://cloud.githubusercontent.com/assets/4606838/11306403/8d45396c-8f7f-11e5-9cc4-95320c81a12f.png)
Can either of you look into this with your fancy shmancy NL-account-access?

**Comment by DavidVorick** [comment]
fixed, though we're not really sure why
