### ISSUE TITLE
Pagination for the wallet transactions in the UI

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#130]
looks like the api already supports pagination - you can request transactions from a set height to a set height. Users might prefer to see a set number though, which would require some backend refactoring.

**Comment by pmknutsen** [comment]
This is not pagination as it returns an unknown number of transactions. To solve the UI issue you definitely need to be able to limit what is returned.

**Comment by DavidVorick** [comment]
what is a sensible limit? 1000?

Even now, the api request itself is not that slow, maybe 1-2 seconds. It's the javascript that is slow. Users might only want to see 25 at a time, but the api should probably be serving a much larger number.

**Comment by pmknutsen** [comment]
The limit should ideally be configurable. For instance:

`/wallet/transactions/limit=10&start=10`

will return the last 10 transactions (1 through 10; where 1 is the most recent transaction).

`/wallet/transactions/limit=10&start=20`

returns the transactions 11 through 20

If you hardcode a limit, how then will I be able to return transactions before that limit?

**Comment by DavidVorick** [comment]
doesn't it make sense to go the other way?

limit=10&start=0 ==> return transactions 0-10?

**Comment by pmknutsen** [comment]
I see your point, but transactions are returned in chronological order. So, in your case `start` actually implies `end`, which I think is more confusing.

In a different # issue, I also suggested this (inspired by other APIs):

Return the last 100 transactions:
GET `/wallet/transactions?size=100&from=100`

and the next 100 transactions:
GET `/wallet/transactions?size=100&from=200`

or, alternatively:

Return the last 100 transactions:
`/wallet/transactions?start=100&end=0`

and the next 100 transactions:
`/wallet/transactions?start=200&end=100`

**Comment by Mingling94** [comment]
Solved by #140
