### ISSUE TITLE
Sia UI just throws errors in the absence of siad

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#14]
Sia UI relies on siad being installed to the PATH of the client running the program. It should give a good warning if siad is not installed rather than attempting to start and throwing a hundred or so errors.

**Comment by Mingling94** [comment]
One can check (within daemon.js) the call process.env['PATH'] I believe to return the string that is the PATH variable

But I don't know how I could check if this variable contains the path to siad within the release folder

Like on my system I have export PATH="$PATH:/cygdrive/c/Users/Ming/Documents/College/Spring 2015/Sia/0.2.0-release.beta" in my .bashrc to add it into the PATH of cygwin, so what sort of javascript string magic would I have to do to be able to check for this folder on OTHER PEOPLE's systems? And further how would I check that specifically siad.exe is there?

**Comment by lukechampine** [comment]
`child_process` should [report an error](http://nodejs.org/api/child_process.html#child_process_event_error) if it can't spawn siad.

**Comment by Mingling94** [comment]
So I don't really understand how the current error-checking works. When I run, why don't I see any of the console.log or console.error results called in daemon.js?

Also this is a great write-up I'm reading through about error-handling for anyone to reference: http://www.joyent.com/developers/node/design/errors
A tl;dr with examples is here: http://www.nodewiz.biz/nodejs-error-handling-pattern/

Am I correct in thinking that this context calls for asynchronous, operational error-handling within daemon.js? Should the process exit if a siad command isn't found?

**Comment by seveibar** [comment]
I think for the specific case of the absence of siad, we just need to detect if the shell exited.

Errors that siad releases during the program should be sent to `ui.notify` to notify the user.

**Comment by DavidVorick** [comment]
It appears that this has become an issue again.

**Comment by Mingling94** [comment]
This and #98 are dealt with

**Comment by DavidVorick** [comment]
It's still an issue. When there's no siad, you don't get a message indicating that siad can't be reached, you get a bunch of spam, it's not even error it's just labeled 'INFO'.

While not typically a problem at startup, it does happen.
