### ISSUE TITLE
Heavily Documented Example Plugin

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#14]
The overview plugin should be our example plugin. It should be heavily documented, with every bit of code being explained in the context of how you make a plugin. We should expect that people will regularly be using the overview plugin as a reference, and so the code should be fully explained and of the highest quality.

Once the overview plugin is ready, we'll open source the test-ui.

I am worried because the API isn't stable yet, but every day we get closer to refactoring the api.

**Comment by Mingling94** [comment]
API's stable!

I was going to write test cases for all the API calls, though I'll hold off on that because you mentioned overhauling the API which could nullify a lot of call-specific javascripting

**Comment by DavidVorick** [comment]
That's what I mean by a stable API. We're overhauling it, therefore it's not stable.
