### ISSUE TITLE
Oversized Sia logo in OS X's status menu.

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia-UI#149]
![screen shot](https://cloud.githubusercontent.com/assets/5420909/11786925/46e2e920-a257-11e5-9484-f0ee62efdf32.png)

**Comment by DavidVorick** [comment]
I blame Apple, the OS should be able to resize as necessary. I'm pretty sure that's what both Linux and Windows does.

heh. We should fix it.

**Comment by VoidingWarranties** [comment]
The icon shouldn't even exist in the status menu unless there are clickable items or other display info in it. Are there actions that the status menu currently provides? If there are none we should remove it.

**Comment by DavidVorick** [comment]
I think it was supposed to have the buttons that allowed you to minimize the window or something.

I'm not sure how it got there, you'd have to talk to Ming.

@Mingling94 ideas?
