### ISSUE TITLE
Replace UI Notification system with OS native notifications

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#150]
https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#notifications-windows-linux-os-x

**Comment by DavidVorick** [comment]
In general I'm against this, mostly because I don't think I have native notifications installed on my  system.

**Comment by DavidVorick** [comment]
Actually, some of that stuff is pretty cool, but I'd rather continue to focus on getting the really critical features ready before we start to implement more 'looks professional' type of stuff.
