### ISSUE TITLE
Decimal precision for price and maximum file size change after reset

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia-UI#151]
e.g. Maximum file size = 5368.71, click reset, Maximum file size = 5368.70912, click save, quit Sia UI, reopen, Maximum file size = 5368.71.

before
![before screen shot](https://cloud.githubusercontent.com/assets/5420909/11787726/4af233c8-a25b-11e5-83b9-8fcee63e142c.png)
after
![after screen shot](https://cloud.githubusercontent.com/assets/5420909/11787738/56d49fd2-a25b-11e5-8c9e-bbbfe8c2e059.png)

**Comment by Mingling94** [comment]
I believe this is with the old release version and is fixed on master.
