### ISSUE TITLE
Add common actions to OS X's menu bar

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia-UI#152]
Some examples I can see being useful (especially if they had corresponding keyboard shortcuts) are "add file", "add folder" which could take you to the existing corresponding pages.

**Comment by DavidVorick** [comment]
I'd rather worry more about stuff like this once we have a designer/UX person working on it, engineers tend to make a lot of clutter when they add features like this.

Also, the core functions aren't all in place (namely, a fully functional file browser), and we should get those working before we work on the smaller details.
