### ISSUE TITLE
Possible permissions issue running Sia-UI through atom-shell for Windows (developer problem)

### ISSUE THREAD

**Issue by zlalvani** [NebulousLabs/Sia-UI#16]
Running atom-shell on the Sia-UI directory gives the following error in the atom-shell console: 

`Not allowed to load local resource: file:///C:/cygwin/home/[my_username]/Sia-UI/site/index.html`

The same error appears when running through Cygwin and the elevated command prompt. Additionally, the DOS command prompt shows the following errors:

`c:\cygwin\home\[my_username]\Sia-UI>[5896:0224/014225:INFO:renderer_main.cc(211)] Renderer process started
[271160:0224/014226:INFO:renderer_main.cc(211)] Renderer process started
[270788:0224/014227:INFO:CONSOLE(0)] "Not allowed to load local resource: file:/
//C:/cygwin/home/[my_username]/Sia-UI/site/index.html", source: data:text/html,chromeweb
data (0)
[270788:0224/014227:ERROR:CONSOLE(2874)] "IndexedDBAgent error: Could not obtain
 database names.", source: chrome-devtools://devtools/devtools.js (2874)`

I'm not sure this is a Sia-UI problem but it's something that we should work on to get Sia-UI to be user friendly.

**Comment by seveibar** [comment]
Not a permissions issue, Sia-UI requires `ruby-haml` and `lessc` to run.

`ruby-haml` can be installed as a ruby gem
`lessc` can be installed using npm

**Comment by DavidVorick** [comment]
is this a developer environment thing or a binary dependency thing?

**Comment by seveibar** [comment]
Developer environment thing

**Comment by Mingling94** [comment]
Wooo we're going to use hamlessc :D

**Comment by seveibar** [comment]
This has been fixed- for future reference this error is due to the project not being built or not being built properly.
