### ISSUE TITLE
Overall UI thoughts

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#18]
.gitignore:

`*.swp` instead of `**/*.swp`. Also, it's a bit disorganized, there's probably a better way to sort things.

---

DEVELOPERS.md:

It's probably good enough to call it Developers.md

"To get started, run 'make dependencies && make"

Ming's brief guide to javascript is unnecessary. It would instead be sufficient to have a section titled "Technologies" or something similar to that, and then talk about using node.js and electron (perhaps with a brief explanation for why they were chosen), along with links to learn more about each. Links to javascript style guides and best practices are also okay, but you don't need much more than links unless there's something the project enforces that isn't really idiomatic.

I think for the most part developers.md just needs to be rewritten.

Developers.md should probably explain something of the general project layout, including stuff like plugin information, sidebar information, dependency handling, and topbar information. Basically, enough information that someone can dive right into what they are most interested in working on without needing to look at a huge portion of the project.

---

README.md:

readme looks fine, just remember that it's targeted at users who want to compile things themselves, maybe monkey around with the CSS a bit, but it's not targeted at developers.

I think it's good though right now.

---

package.json:

the "scripts" seem a bit cluttered/disorganized. Otherwise it all looks pretty good. As the project matures further, the scripts should probably be cleaned up, but for now it's fine.

---

app/index.js:

line 24, `appIcon.setToolTip`: can you explain that further? What does it do, and should be change the words?

line 41: `mainWindow.focus()`: is there a specific reason that the UI needs to grab focus? I generally find it annoying when my apps try to grab focus after I open them. I'm typically multitasking.

---

app/index.html:

Is there any reason that the javascript is included at the bottom of the file?

The comment `save the config as is` is a bit misleading. The function is `UI.close`, and while it does save the config, index.html is really the wrong place to say that. The two comments about the UI startup and closing are probably not needed at all, it's pretty clear what's happening in the code.

---

app/assets/logo:

I find it interesting that we have the logo in both a png and an svg. Is there any reason that we need both?

---

app/css/general.css:

don't import fonts via a url, have them downloaded and in the assets folder. We can't assume that the user will always have an internet connection when working in Sia, plus it causes huge latencies that aren't necessary. (this is specifically talking about line 12)

Assuming that there will be at most 5 sidebar buttons is bad. I think 8 is a safer starting point, but as people start making their own plugins that number might go up substantially.

---

app/plugins/Overview:

You should probably create the standard webpage folders, especially since it's example code that we can reasonably expect people to copy.

have a `css/` and `js/` and `assets/` folder, and put the button in the assets folder. All of the html can stay at the top level.

---

app/plugins/Overview/index.html

line 6 isn't tabbed out correctly

---

app/plugins/Overview/overview.css

don't import the fonts from a url

---

app/plugins/Overview/overview.js

variable names 'b', 'p', and 'h' are bad.

I'm not sure I understand how the api calls work. You've got an array of calls that you send every second, and then you get a list of results back every second? Seems weird to me, and probably could be improved.

What happens if you just want to send a single call, and you want to see the response (like the renter renaming the file, for example)

---

app/js/UI.js:

I feel like the update code and the zoom code belong in different files. Maybe not.

For example, it seems like the zoom code would be better suited to config.js. The upload stuff might deserve its own file.

On line 63, its confusing why you are taking a variable named cfg, and then setting `config=cfg;` This could probably use a comment.

---

app/js/daemonManager.js:

the functions `printCall` and `testCalls` seem to be out of place. Where possible, testing code should not reside next to production code. The one exception for this is asserts, but that's only because there's no way around it. Testing code should probably be in a separate file. I'm not if 'daemonManager_test.js' is a legal filename, or if there's some other structure you'd need to follow, but ideally you could find another place for the testing code.

The commant `// Encapsulated 'private' elements` is not helpful. It would be better to explain what the elements are and why they exist, though in this case their name alone seems to be nearly sufficient.

I don't really understand the purpose of the first half of the `ifSiad` function. Seems a bit hacky and like there is a better way to do things.

line 87: `// stop() stops the daemon using its API` might be more clear. What you have now is wordy.

The docstring for `function addPort` is not helpful.

---

I find it mildly confusing that the plugin stuff is split into 3 files, but I'm not sure if having everything in one file would be better. I still don't really understand how the plugin loading works.

**Comment by Mingling94** [comment]
## Developers.md and README.md

Should I move the structure description from README to Developers.md and make it more descriptive? The README being the landing text on a github repo should just go over summary, setup, and running, right?

## package.json

I would organize the package.json, but [npm comments are a bit messy](http://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install)

## app/index.js

line 24: It [sets the hover text for this tray icon.](http://electron.atom.io/docs/v0.29.0/api/tray/)

## app/index.html

JS at the bottom of an html file is something I picked up initially actually from viewing Aaron's Sunfish code. Loading markup and style is trivial, but JS takes a while and will block elements as it's loaded synchronously. In other words, this has less white-screen glitchiness at the beginning of load.

## app/assets/logo:

Electron uses an [image class](http://electron.atom.io/docs/v0.29.0/api/native-image/), for the most part internally, but they don't support SVG yet. 

## app/css/general.css:

I'm not sure where those css comments about 5 buttons came from. The UI doesn't even seem to enforce min-height/width standards.

## app/js/UI.js:

You might be right on the placement of the zoom code and update button, but until I implement update and settings buttons, I won't know.

**Comment by DavidVorick** [comment]
Yeah, README.md should just be summary, setup, and running. Developers.md should go into more detail about the general architecture.

About the tray: the popup text should probably just be "Sia - Decentralized Storage"
