### ISSUE TITLE
Sia build server and batch file to get bleeding edge Sia binary

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#18]
Forest knows what I'm talking about

**Comment by cyrozap** [comment]
Windows doesn't have any built-in web downloading programs like `wget` or `curl`, so the batch file isn't going to happen.

**Comment by cyrozap** [comment]
The build server has been configured.

**Comment by seveibar** [comment]
Woot! Details for the build server are on the slack.

Great job thanks!
