### ISSUE TITLE
pb npm run release

### ISSUE THREAD

**Issue by xavierle** [NebulousLabs/Sia-UI#189]
i am just trying the readme files commands to get an understanding of the structure of Sia project

https://github.com/NebulousLabs/Sia-UI/tree/v0.4.8-beta

actually the command npm run release fails

Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "release"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! Sia-UI-beta@0.4.6-beta release: `./release.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the Sia-UI-beta@0.4.6-beta release script './release.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Sia-UI-beta package,
npm ERR! not with npm itself.

what is surprising me is that i downloaded 0.4.8 tags
and that the code is looking for 0.4.6 release

if someone have an idea ?

**Comment by DavidVorick** [comment]
huh yeah, weird that it's looking for the 0.4.8 release. I think we are at an awkward in-between stage of development, but we'll try to get that fixed asap.

In the meantime, you should probably have 'siad' built on your own. https://github.com/NebulousLabs/Sia/blob/master/doc/Developers.md

**Comment by xavierle** [comment]
i made again a try based on git clone and not zip download

run start seems to get nicely

**Comment by DavidVorick** [comment]
It's working now because Luke synchronized the repositories :)
