### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#2]
Use something like atom-shell so that we can distribute a desktop application

for now, the daemon should start when the app starts and close when the app closes. If the user opens two instances, a notifications should appear indicating that a daemon is already running. (you can test for this by pinging the port that the daemon is listening on)

at some point, the daemon should just run in the background and keep running after the window is closed. If it's not too hard, maybe that should just happen right away.

**Comment by seveibar** [comment]
With atom-shell the background process shouldn't be hard- I'll do some probing this week

**Comment by seveibar** [comment]
The UI now starts and stops the daemon process, application is created as desktop app etc.
