### ISSUE TITLE
Use grunt to install dependencies

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#20]
We're completely on the npm stack! That means we can start using grunt!

http://gruntjs.com/

The two dependencies that will be easy are `lessc` and `haml-coffee`. The way this build manager works is if you run `grunt`, the program will automatically install all the dependencies you need.

**Comment by DavidVorick** [comment]
careful on the toolchain. Where possible, you should stick to the tried and true stuff like make. Newfangled stuff tends not to last as long.

**Comment by seveibar** [comment]
We already rely on the node package manager which gruntjs is available through and integrates with.
Grunt is also one of the only ways (and definitely the easiest way) to complete #21.

Grunt will also really help improve the cross-platform situation- we finally got the windows machines working today and it seems that it would be very tricky to maintain makefiles, which are not a crossplatform solution (even cygwin often has problems).

**Comment by seveibar** [comment]
joey fixed this
