### ISSUE TITLE
Passphrase saving even if wrong

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#200]
Yosemite Darwin 0.5.1

Saving and sending siad the password and unlock command seems to work fine, but there is no going back if you put in the wrong password. If you fat finger it, you don't get the chance to change the string and you are condemned to just the get Wrong Password error.

Fix: Make Sia forget the password if you enter the wrong one
       or
       Make Sia save the password only if it's the correct one

**Comment by lukechampine** [comment]
Thanks for reporting these.
We're probably just going to remove the "save password" functionality for the time being. It's too important a feature for it to be buggy like this.
