### ISSUE TITLE
Doubleclicking on passphrase to copy string is buggy

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#201]
Yosemite Darwin 0.5.1

Passphrase Generation dialog:
If you double-click on the passphrase, here is what you get back as a copied string:

`"password": "balding motherly roles pram lodge knuckle different haunted salads drowning tell alpine rejoices potato intended sleepless jeers cedar optical upgrade stunning tubes tissue hedgehog rumble moon razor jolted against I've recorded this in a safe place!"`

The "I've recorded this in a safe place!" button label sneaks into the selection area.

Fix: Make sure doubleclicking the string does not select the button label as well

**Comment by lukechampine** [comment]
hmm. I can't reproduce this on Linux. @VoidingWarranties?

**Comment by VoidingWarranties** [comment]
I can't reproduce either on El Capitan. Maybe it's Yosemite specific?

**Comment by TacoByte** [comment]
This seems to have been fixed in the latest silent update that happened yesterday.
