### ISSUE TITLE
Passphrase Generation Dialog doesn't go away when prompted to close

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#202]
Yosemite Darwin 0.5.1

Passphrase Generation Dialog:
Clicking the close window cross on the upper right part of the dialog does not close the dialog box.
Clicking the "I've recorded this in a safe place!" sentence does not close the dialog box.

The dialog box never goes away. You can still use Sia, and the dialog box doesn't follow you on the other panels, but it's there when you come back. Waiting. Lurking. Impervious to your clicks.

Fix: fix

**Comment by DavidVorick** [comment]
It just wants to be your friend. It doesn't get to see people often, only the first time they ever use Sia.

in all seriousness, thanks for pointing this out.

**Comment by lukechampine** [comment]
this was due to the "save password" dialog being erroneously removed in the release binaries.
I've patched them now. Can you redownload and try again?

**Comment by TacoByte** [comment]
Yeah, it's fixed. Now I feel bad for making it go away...

**Comment by lukechampine** [comment]
It will live on in our hearts.
