### ISSUE TITLE
Paste ASCII File dialog loads inside menu bar

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#203]
Yosemite Darwin 0.5.1

File Dropdown Menu:
If I select Paste ASCII File, nothing seems to happen.

It turns out that when I drop down the file menu again, the Paste ASCII File dialog is actually loaded inside the menu bar, just chilling there.

Fix: Turn the Paste ASCII File dialog into an actual popup window.

**Comment by Mingling94** [comment]
Does the file menu hide itself as soon as you select Paste ASCII File? If so a bug was introduced somewhere.

Popup windows with input boxes [aren't supported by electron](http://electron.atom.io/docs/v0.36.0/api/dialog/), so applying your suggested fix would be reinventing the wheel a bit.

**Comment by TacoByte** [comment]
Yes, the file menu closes. As usually expected when selecting something in a dropdown and waiting for whatever is meant to happen?

Oooh, so you can't use something like the dialog you use for the Passphrase Generation popup? That's too bad, but at least if you get the menu not to hide, you could take some time to implement something else later.

**Comment by Mingling94** [comment]
Yah no selecting "Past ASCII File" should just transform the dropdown, not close it.

We could use the popup, but manually handling popups is wheel-reinventing. There's probably some library we should use to make nice looking popups.

**Comment by Mingling94** [comment]
Wait, I can't replicate this from the master branch, didn't try from release. 
![sia-ui_009](https://cloud.githubusercontent.com/assets/4606838/12770093/7a086a40-ca58-11e5-898d-7b78e770877f.png)
![sia-ui_010](https://cloud.githubusercontent.com/assets/4606838/12770095/7bffe7ec-ca58-11e5-930c-e9cc7ecd15c7.png)

@DavidVorick @lukechampine @VoidingWarranties thoughts?
