### ISSUE TITLE
Siad needs to be running

### ISSUE THREAD

**Issue by JoshuaMurphynz** [NebulousLabs/Sia-UI#205]
when i run

Sia-UI

I get an error saying that siad needs to be running.

This should be started automatically

**Comment by lukechampine** [comment]
siad is started automatically, though it can take a while to startup. Personally, I prefer to run siad separately from the UI.

**Comment by DavidVorick** [comment]
I do think that the UI should not close 'siad'. People were originally confused by the behavior that 'siad' would not shut down when the UI was closed, but it's important to the hostdb that 'siad' be running most of the time otherwise it won't know which hosts have good uptime.

**Comment by avahowell** [comment]
This behavior has been specified and implemented as of #220 and #222.  I am therefore closing this issue.
