### ISSUE TITLE
OS X System tray icon is broken

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#206]
Capitan 0.5.1

The Sia system tray icon is broken

1) The icon used is an oversized and buggy Sia wordmark rather than the usual small monochrome logo

![siatray](https://cloud.githubusercontent.com/assets/8594622/12884243/3d638ef4-ce5d-11e5-8cdb-322468e2dfdf.jpg)

2) Clicking doesn't do anything

This ties in with the whole siad running in the background thing.
Closing the UI should not quit siad and you should be able to launch the UI again and do other things through an appropriate system tray icon dropdown menu with links to the different tabs (Renter, Host, Wallet, Quit Sia (Are you sure? You might lose contracts. Yes/No), etc...)

**Comment by lukechampine** [comment]
fixed by #212
