### ISSUE TITLE
Proposal for handling UI exit

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia-UI#213]
![ui_close_proposal](https://cloud.githubusercontent.com/assets/1565499/13099654/4f6cf396-d4e9-11e5-97d1-bd17c45fe65c.png)

The above is just a mockup (ignore that I'm using 0.4.8 as backdrop)

This is a proposal for how to deal with user either wanting to just exit the UI, or shut down Sia altogether.

I removed the window frame (should also add a border)
An X was put back in the upper right hand corner
A Quit button was added on the Overview page

The intended behavior is:
Pressing the X minimizes the UI
Pressing "Quit" will exit the UI _and_ `siad`

Selecting "Quit" should probably also launch a dialog warning user that the host will be shut down as well, and then provide a Confirm button.

**Comment by lukechampine** [comment]
@johnathanhowell is planning on implementing the approach you described in #210, where closing minimizes to tray and the tray contains a "Quit" option. I think this is a good approach, in line with how many apps work when they need to run in the background.

**Comment by VoidingWarranties** [comment]
For desired behavior when quitting the UI, what about this?
- If there is already an instance of `siad` running (on the default port), do not quit `siad` when quitting the UI.
- If no instance of `siad` is running when the UI starts, the UI starts one and quits it when the UI quits.

This was the desired behavior @DavidVorick mentioned a few weeks ago when we were discussing it offline.

**Comment by pmknutsen** [comment]
@VoidingWarranties A remaining problem is users that run a host, started when the UI is opened. When the UI is closed, the host shuts down too in your scheme.

**Comment by Mingling94** [comment]
@VoidingWarranties There is already an option in the siad wrapper and defaulted to `false` in the UI called `detached`.
if `true` - run siad as either a detached, background process and doesn't exit it with the UI's closing.
if `false` - start siad if not already running, close upon the UI's closing.

I didn't make a settings page/plugin ( #47  ) to change said setting, but if you changed it in the config.json manually, you'd see the results.

**Comment by Mingling94** [comment]
I think this suggestion of providing buttons to close siad with the UI is approaching the problem from a more action-based perspective, but I'd sooner like to see a settings plugin where one can change the persistence of siad.

This means that hosts could set `detached` to `true` and renters/whoever else could set/leave it as `false`

**Comment by VoidingWarranties** [comment]
@pmknutsen hmmm good point. I like your suggested approach. Then again maybe the host is somewhat of a special case and we could implement something like:
- If the user isn't running a host, quitting the UI quits `siad` too.
- If the user is running a host, quitting the UI brings up the dialog:
  "It looks like you're running a host. Quitting Sia will also stop your host. Would you like to minimize Sia instead?" with the buttons "minimize" and "quit"

**Comment by pmknutsen** [comment]
@VoidingWarranties Consider also renters and "power users" who want to be up to date on file repairs and blockchain synchronization. I think a shutdown of `siad` should always be very explicit, with a "Quit" button or similar (unless a different behavior is set by the user in a Settings plugin as suggested by @Mingling94).

**Comment by VoidingWarranties** [comment]
Okay, sounds good!

**Comment by pmknutsen** [comment]
Anyway, @johnathanhowell seems to have made improvements with #214 so I'll close this for now.
