### ISSUE TITLE
Issues running from source

### ISSUE THREAD

**Issue by LiteBit** [NebulousLabs/Sia-UI#215]
Following readme.md instructions and getting 
`~/Sia-UI $ npm install`
`Illegal instruction`
Same error when running from base directory:
`$ npm install`
`Illegal instruction`

Working on rasbian wheezy. 
Installed node.js and npm like this:

**Install npm**

   `$ sudo apt-get install npm`

**Install NodeJS**

   `$ curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -`
   `$ sudo apt-get install -y nodejs`

**Comment by DavidVorick** [comment]
what version of node are you running? You need version 4.4 or later if I remember correctly

**Comment by lukechampine** [comment]
closing as outdated
