### ISSUE TITLE
Issues running Sia-UI 

### ISSUE THREAD

**Issue by Jzarecta** [NebulousLabs/Sia-UI#216]
When Running Sia-UI it asked me for siad to be running, once I select the siad file under the resources/Sia/app/siad it returns the following:

```
(node) warning: possible EventEmitter memory leak detected. 11 did-finish-load listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at signal (/home/user/Downloads/Sia/resources/app/js/mainjs/initSiad.js:22:6)
    at /home/user/Downloads/Sia/resources/app/js/mainjs/initSiad.js:44:3
    at /home/user/Downloads/Sia/resources/app/node_modules/sia.js/js/sia.js:98:9
    at /home/user/Downloads/Sia/resources/app/node_modules/sia.js/js/sia.js:83:9
    at Request._callback (/home/user/Downloads/Sia/resources/app/node_modules/sia.js/js/sia.js:69:9)
    at Request.self.callback (/home/user/Downloads/Sia/resources/app/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/user/Downloads/Sia/resources/app/node_modules/request/request.js:1036:10)
```

I only get a white screen. Please help.

**Comment by DavidVorick** [comment]
This is an issue that has been around for a while, but I don't think anyone has presented that error message, perhaps it will help us get to the bottom faster.

Development on the GUI is stalled for the next month or so, we are actively working on pushing out a 1.0 of the daemon, so that developers can have a stable platform on which to build applications. I expect GUI development to resume shortly.

**Comment by Jzarecta** [comment]
Siad by itself gave me the following output:

```
$ Sia/resources/app/Sia/siad
Loading...
(1/7) Loading gateway...
(2/7) Loading consensus...
(3/7) Loading transaction pool...
(4/7) Loading wallet...
(5/7) Loading miner...
(6/7) Loading host...
(7/7) Loading renter...
Finished loading in 0.046854794000000005 seconds
```

Any CLI instrucctions to pass around so I can ioperate it without eh UI?

**Comment by DavidVorick** [comment]
Yeah, there's a tool called `siac` that can do almost everything the GUI can (and also has some extra functionality). Siac has some great help menus, `siac -h` will list commands, `siac [command] -h` will list help for that command, if you like exploring then siac should be both fun and friendly.

Siac should be included next to siad. You can also get the most recent release here: https://github.com/NebulousLabs/Sia/releases

**Comment by Jzarecta** [comment]
yeah I have been working with siac, on the other hand, I have google the issue, and seems to be some coding bug, doing nested listeners causes the memory leak report. There are some workarounds but someone with experience on JS/Node/Meteor should take a look to the actual code. 
http://stackoverflow.com/a/16222062

**Comment by trismegistis** [comment]
Hi does this UI work with the latest 2 days ago release? 0.6?

**Comment by lukechampine** [comment]
No. The API has changed a lot. A new UI release is forthcoming.
