### ISSUE TITLE
Feature: Info about blockchain synchro at first startup

### ISSUE THREAD

**Issue by martinkrung** [NebulousLabs/Sia-UI#219]
I just installed sia and sent some SC from poloniex to my address. I still do not see my coin in my wallet and the reason is quite simple: My local blockchain is just at height 34500, the transaction will be at around 45,200. 

So beeing an bitcoin veteran this is clear to me,  but if somebody has no clue you must inform at first startup that the sofware is first synchronizing the blockchain. at best you will, during synchronizing, show an estimate end time of the synchro process.

thanks

**Comment by lukechampine** [comment]
We already support this in `siac`, but it would be a good feature for the UI to have as well. A time estimate would be trickier. We could rig one up without too much trouble, but it wouldn't be very accurate.

**Comment by Mingling94** [comment]
That's alright, UI time estimates for process completion times are never
accurate.

**Comment by droghio** [comment]
Resolved in #360
