### ISSUE TITLE
Wallet plugin should have feedback for blockchain status or wallet rescan

### ISSUE THREAD

**Issue by avahowell** [NebulousLabs/Sia-UI#230]
As it is now, the wallet will simply show 0 balance if the blockchain isn't synchronized or if the wallet is being re-scanned.  It's probably a good idea to show some sort of feedback if these things are happening instead of simply showing the current balance (zero).

**Comment by lukechampine** [comment]
cf. https://github.com/NebulousLabs/Sia/pull/1185

**Comment by DavidVorick** [comment]
what is the status on this?

**Comment by lukechampine** [comment]
Not likely to be implemented in the short-term.
