### ISSUE TITLE
Use an OS-standard location for siad's `--sia-directory`

### ISSUE THREAD

**Issue by avahowell** [NebulousLabs/Sia-UI#243]
An OSX user recently pointed out that since the default Sia `datadir` is located in the App bundle, there's no way of upgrading their UI release without wiping out Sia's data.  Since a recent pull request to `sia.js`, it's now possible to set `--sia-directory` independently from `siad`'s path.  Using an OS-standard data location is the obvious solution to this problem (`ApplicationSupport` for OSX, `%APPDATA%` for windows, `~/.local/share/sia` for linux), but there are caveats with this as discussed in https://github.com/NebulousLabs/Sia/issues/1070.  In order to safely implement this change, `siad` should add a lockfile to the `sia-directory` to ensure only one instance of `siad` can be running on a given directory.

In the mean time, we can guide users through the process of migrating their data from the app bundle to the new location upon 1.0's release.  This process is easier for Windows and Linux users since they can directly replace the binary inside their release folder, unlike OSX users.

**Comment by DavidVorick** [comment]
There might be a way to do in-place upgrades from within the app, which would be the preferred method. Using a standard data directory has previously been associated with losing money. Now that we have seed based wallets it's much less of a risk, but still an issue if we end up with multiple instances of `siad` open at the same time.

You can use things like file locks to help protect against this problem, but if we start using a common directory we also lose portability and we lose the ability for a user to easily have multiple wallets on the same machine.

**Comment by VoidingWarranties** [comment]
Closed in #306.
