### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by roymj88** [NebulousLabs/Sia-UI#248]
Hi,

Tried installing using the steps given:

```
git clone https://github.com/NebulousLabs/Sia-UI.git
npm install
npm start
```

But it shows the following error:

```
Uncaught Exception:
TypeError: protocol.interceptBufferProtocol is not a function
    at initializeProtocolHook (/home/roy/projects/Sia-UI/node_modules/electron-compile/lib/protocol-hook.js:115:12)
    at EventEmitter.protoify (/home/roy/projects/Sia-UI/node_modules/electron-compile/lib/config-parser.js:317:9)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

Note: I am on ubuntu with node version `v6.2.2` and npm version`3.9.5`

Kindly advice as to what should be done.

![sc](https://cloud.githubusercontent.com/assets/2633799/16172663/6dc590d8-35aa-11e6-8139-3e5d15d519bf.png)

**Comment by SonicWizard** [comment]
I get the same thing.

**Comment by avahowell** [comment]
I'm pretty sure this is an issue in the upstream package `electron-prebuilt-compile`, as such I've made an issue here: https://github.com/electron/electron-compile/issues/107.

As of right now we've moved the build system to webpack.  This issue should be resolved, so I'm closing it.

**Comment by roymj88** [comment]
@johnathanhowell : So i just pull the latest and things should be fine? Please advice.

**Comment by avahowell** [comment]
Yes, pull the latest master and 

`npm install`
`npm run start`
