### ISSUE TITLE
Please add more documentation regarding how to configure host and set up storage space for renting

### ISSUE THREAD

**Issue by roymj88** [NebulousLabs/Sia-UI#277]
The current documentation do not contain any detail regarding how to configure the storage space and set up price and modify storage space, location etc using sia-ui. Please update or add more info regarding the same.

**Comment by lukechampine** [comment]
A hosting plugin is in the works. It will be included in the 1.0 release.

**Comment by roymj88** [comment]
@lukechampine : Okay cool. Will wait for it.

**Comment by DavidVorick** [comment]
is this issue considered resolved now that there is a hosting plugin available?

**Comment by lukechampine** [comment]
I'll close this for now. If people have specific feedback on changes they'd like to see in the hosting plugin, then they can open a new issue.
