### ISSUE TITLE
UI Compilation Broken on Windows

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia-UI#284]
After cloning the repo, running `npm install` and then `npm start`webpack successfully runs but electron fails to load with the following issue:

![electronerror](https://cloud.githubusercontent.com/assets/3069222/16311020/d3106112-393c-11e6-98af-dd7a4430d3ae.PNG)

The problem seems to be in the JSONScheme validator being incorrectly packaged by webpack. This is likely connected to this issue https://github.com/request/request/issues/1920. From the issue, the fix is to manually downgrade the request library that uses the validator by running `npm install request@2.65.0`

**Comment by DavidVorick** [comment]
Is this something we're interested in fixing?

**Comment by avahowell** [comment]
Not for now. A lot has changed since this issue was opened also, so it's possible that compilation works on windows now. Closing this.
