### ISSUE TITLE
Revenge of the Unlock wallet dialog does not go away

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#297]
In the same vein as #273 

RC2 Darwin

After entering my password, dialog is stuck on "Unlocking your wallet..."
My wallet seems unlocked (can see transaction history and balance in greyed out background)
However, the app still behaves as if it were locked: Hosting tab still complains "You must unlock the wallet to host files" and Overview still shows the status as Locked and balance as "--"

**Comment by avahowell** [comment]
The wallet is actually still locked.  It takes a long time to unlock your wallet (minutes)

**Comment by TacoByte** [comment]
I don't remember it ever taking this long, but you may be right. I'm restarting the process now and I'll check back in soon

**Comment by avahowell** [comment]
The amount of time it takes to unlock depends on how many addresses you have as well as your block height.

**Comment by TacoByte** [comment]
Forgive me, you are right. Ok, chalk this up to my impatience. It did unlock finally after 6-8 minutes. A "be patient!" warning that this is a long process or even better a rough percentage status would definitely help, though.

**Comment by avahowell** [comment]
There are planned optimizations for the Sia back-end to make unlocking near instant.  I'll add a more descriptive 'please wait...' text in the mean time.  Thanks for making these bug reports.

**Comment by lukechampine** [comment]
This is partially addressed on the backend: siad will print how many blocks the wallet has processed. No API support though.
