### ISSUE TITLE
Fatal error flood after trying to upload a folder

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#299]
RC2 Darwin

This happened after trying to upload a folder.

Sia lost the files list and can't see the files I uploaded before. Luckily just test files, but this is pretty bad.

I am also getting flooded with this same error over and over again, i closed around 30 of these windows:

**Sia-UI Files Error
Failed to encode response.**

 Quitting and restarting Sia doesn't fix the issue

**Comment by avahowell** [comment]
can you post the results of the "renter" command in the Terminal, or the results of ./siac renter?

**Comment by lukechampine** [comment]
drat, we don't log the error here:

``` go
func writeJSON(w http.ResponseWriter, obj interface{}) {
        w.Header().Set("Content-Type", "application/json; charset=utf-8")
        if json.NewEncoder(w).Encode(obj) != nil {
                http.Error(w, "Failed to encode response", http.StatusInternalServerError)
        }
}
```

I'll fix this on the backend.

**Comment by TacoByte** [comment]
renter

Renter info:
    Storage Spending:  438.9 mS
    Upload Spending:   414 mS
    Download Spending: 252.7 mS
    Unspent Funds:     66.47 SC
    Total Allocated:   67.57 SC

Could not get file list: Failed to encode response

**Comment by TacoByte** [comment]
also got a bunch of

`2016/06/25 18:39:55.064208 repair.go:301: failed to upload to host 120.76.30.60:9982: host did not accept revision: proposed file contract revision does not correctly add to the host's valid proof output`
