### ISSUE TITLE
UI Issue, Wallet has no Back Button when trying to exit adding an Existing Wallet

### ISSUE THREAD

**Issue by applecrusher** [NebulousLabs/Sia-UI#325]
I accidently clicked to try to add an existing wallet, but I want to add a new wallet. However, I am prompted for a password which I don't have and there is no back button to go back to add a new wallet.
<img width="1022" alt="screen shot 2016-06-29 at 2 16 00 am" src="https://cloud.githubusercontent.com/assets/1963860/16442291/757bb954-3d9f-11e6-9276-3d98bed64bf2.png">

**Comment by avahowell** [comment]
There is currently no way in the UI of destroying and re-initializing your wallet.  You can close the UI, navigate to your data directory (in %APPDATA%/Sia-UI/sia on windows, Application Support/Sia-UI/sia on osx and ~/.config/Sia-UI/sia on linux), and delete the 'wallet' folder.  After that the wallet plugin will present you with the steps to create a new wallet.

Wallet re-initialization will be added as a feature in an upcoming release

**Comment by avahowell** [comment]
Closing, re-initialization is now supported with `wallet init --force`.
