### ISSUE TITLE
sia icon in the system tray is non-functional

### ISSUE THREAD

**Issue by roymj88** [NebulousLabs/Sia-UI#326]
'Hide Sia' and 'Quit Sia' links seems to have no function attached to it. The icon still remains in the tray.

![sia](https://cloud.githubusercontent.com/assets/2633799/16443939/18ad51f6-3df9-11e6-8df1-25db39858e98.png)

**Comment by avahowell** [comment]
Does the UI stay running if you close the main window?

**Comment by avahowell** [comment]
I have not been able to reproduce this problem, closing the issue.
