### ISSUE TITLE
Lock wallet button asks for password to unlock wallet

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#327]
I unlocked my wallet. When trying to lock it back, I get prompted for my password in order to unlock it. I enter my password, and my wallet just stays in the unlocked state.

**Comment by avahowell** [comment]
It's actually just that your wallet is locked.  The lock button isn't prompting you for your password, rather it's locking your wallet, sending the wallet plugin back to the 'locked' state and displaying the "Wallet locked" unlock prompt.

**Comment by TacoByte** [comment]
Oooooooooh right! :) Damn that was silly
