### ISSUE TITLE
Add an indicator on the wallet page if the blockchain is still being downloaded

### ISSUE THREAD

**Issue by AdamBLevine** [NebulousLabs/Sia-UI#329]
A normal user downloading and installing Sia-UI will generally want to send themselves some SIA from an exchange to get started.  Until the blockchain has been downloaded, their wallet will not see their transaction and it's very confusing trying to figure out why your funds are missing.  This is exacerbated because every time you click "Receive" it generates a unique payment address, so the user can not know if they've mis-copied or made some other mistake when in reality the wallet is just still downloading the blockchain.

Add some kind of indication or notification to the wallet page alerting users that transactions won't be detected by the wallet until they've finished downloading the blockchain.

**Comment by avahowell** [comment]
A status indicator in the top bar would probably be helpful for this, along with a notification in the wallet plugin.

**Comment by AdamBLevine** [comment]
That would do it, thanks for the quick response!

**Comment by avahowell** [comment]
Closed with #349
