### ISSUE TITLE
Allow a different quick-access password to be used instead of the full 28 word seed for unlocking the wallet

### ISSUE THREAD

**Issue by AdamBLevine** [NebulousLabs/Sia-UI#332]
I appreciate the need for security but it would be much better if I could use a seperate human memorable password to encrypt the local wallet instead of using the full seed.

**Comment by lukechampine** [comment]
This is possible when using siac, but it's not supported (yet) when using Sia-UI.
To accomplish this, when you create a new wallet, do so with `siac wallet init -p`. You will then be prompted for an encryption password, distinct from the passphrase. You can then continue using this wallet from the UI as usual.

**Comment by ANDREYCHEREPOV** [comment]
я скачал кошелёк а пароль из 28 символов не сохранил можно ли опять скачать будет новый пароль  если нет что делать?

**Comment by DavidVorick** [comment]
@ANDREYCHEREPOV that really deserves its own issue. You should be able to load a seed from the wallet screen after you create a new wallet.

**Comment by ANDREYCHEREPOV** [comment]
пароль для кошелька где его взять?

**Comment by avahowell** [comment]
Closing, this was implemented in #526
