### ISSUE TITLE
Buying 10gb of storage deducted significantly more SC than the quoted price.

### ISSUE THREAD

**Issue by AdamBLevine** [NebulousLabs/Sia-UI#333]
I was quoted about 8000sc for 10gb of storage but looking at my balance now, slightly more than 14,000sc was deducted.   If there's a valid reason why this happened it should be explained to me before I click the button that executes the irreversible action.   

There was mention that anything unused would be returned but I have no idea what I've even really bought besides "10gb" - Was that payment for a month?  It should say exactly what the user is buying.

This all falls under expectation management, you need to tell users what's going to happen before they make the decision to do it and then it needs to happen as you've specified and they agreed to.

**Comment by TacoByte** [comment]
#328 and #330

**Comment by avahowell** [comment]
fixed in #409
