### ISSUE TITLE
I can not search for or download folders

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#334]
Folder names are not included in search results
I can not download or erase whole folders (no cloud and garbage can icons)

**Comment by DavidVorick** [comment]
Deletion is currently not working very well on the backend, might be worth removing it from the UI until the bugs are fixed.

Will be frustrating for the user, but not as frustrating as losing a bunch of files due to a buggy delete call on one of them.

**Comment by avahowell** [comment]
Fixed in #441
