### ISSUE TITLE
Enable Changing Zoom

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#34]
#23 was solved because adjusting the UI's zoom factor through Electron's webframe library was found to be the cause of the plugin webviews not sizing up to the whole mainbar height and width. Thus, I removed auto adjusting the zoom factor.

**Comment by DavidVorick** [comment]
oh, you fixed the zoom by removing it altogether. ok.

**Comment by Mingling94** [comment]
Note to self, see if zoom can be re-enabled sometime: https://github.com/atom/electron/pull/3010

**Comment by Mingling94** [comment]
#47 should really be completed before attempting this issue

**Comment by DavidVorick** [comment]
I'm going to set this aside as 'okay as is' for the near future. I'm sure at some point we'll get users complaining about it again.
