### ISSUE TITLE
Minor Files UI Glitch

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia-UI#340]
Discovery goes to crypto.long on the Slack:

**crypto.long:** minor O/S=Ubuntu 16.04 LTE, UI 1.0.0 and Siad 1.0.0. If you click the Files nav option, then Search Files, don't perform a search and then click once on Buy Storage, the search field remains on the screen above the phrase 'Buy storage on the SIA Decentralized Network'.

**Comment by avahowell** [comment]
fixed in #343
