### ISSUE TITLE
Cannot Upload Individual files in Linux/Windows

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia-UI#341]
Discovery of this issue goes to thapgich in the Slack. On Linux and Windows you cannot upload files, only folders. This has to due to a limitation of Electron. From http://electron.atom.io/docs/api/dialog/:

**Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector,  so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be  shown.**

**Comment by Fornax96** [comment]
![image](https://cloud.githubusercontent.com/assets/1247928/16502373/588cf360-3f0e-11e6-9dca-ce5588e41bd5.png)

EDIT: I also can't multi select (With shift or ctrl pressed). This needs some work

**Comment by avahowell** [comment]
@droghio has a pr that should come in soon that fixes this issue.  There will be two buttons that drop down from 'Upload', 'Upload Files' and 'Upload Folder'.  For now, you can drag and drop files into the renter to upload them.

**Comment by avahowell** [comment]
closed via #350
