### ISSUE TITLE
Add Shapeshift.io support to wallet

### ISSUE THREAD

**Issue by TacoByte** [NebulousLabs/Sia-UI#347]
Hooray, https://shapeshift.io/#/coins now supports Siacoin!

With a proper plugin/enhancement, users will be able to buy storage space directly with Bitcoin! You could even let people withdraw what they make from hosting directly into BTC.

**Comment by Fornax96** [comment]
This should be easy, just add a new tab with an iframe. In the iframe you load this page:
`https://shapeshift.io/shifty.html?destination=[Siacoin wallet address]&output=SC`

And you fill the `destination` field with a generated address from the siad API

**Comment by lukechampine** [comment]
We probably will not create this plugin ourselves (to avoid favoritism), but it sounds like a great opportunity for a community member to write a plugin.

**Comment by avahowell** [comment]
Closing this issue since we're not planning on adding shapeshift support directly to the wallet (as @lukechampine mentioned- favoritism).

**Comment by Fornax96** [comment]
I'll try my hand at a plugin this evening. The plugin tutorial is really good, I hadn't even looked at it before.

**Comment by avahowell** [comment]
It's worth noting that the plugin tutorial is outdated, the IPC stuff has been replaced with `SiaAPI` and notifications have been removed. Plugins are still just webpages. You can read about `SiaAPI` here: https://github.com/NebulousLabs/Sia-UI/blob/master/doc/spec/PluginAPI.md.
