### ISSUE TITLE
siad crashes whenever trying to unlock wallet

### ISSUE THREAD

**Issue by bitcoincoltd** [NebulousLabs/Sia-UI#356]
I'm running siad headless on a Digitalocean 512MB RAM node and every time I try to unlock the wallet it crashes siad.

`curl -A "Sia-Agent" "localhost:9980/wallet/unlock" --data "encryptionpassword=mypassword"`

The message siad gives before exiting:

```
Rescanning consensus set...
Scanned to height 46039...Killed
```

**Comment by pmknutsen** [comment]
Increase ram or swap
1. jul. 2016 3:42 p.m. skrev "Bitcoin Co. Ltd." notifications@github.com:

**Comment by Fornax96** [comment]
Killed means that the kernel killed the process for using too much memory. 

Sia needs a machine with _at least_ 4 GB of RAM _and_ 4 GB of swap.

**Comment by bitcoincoltd** [comment]
4GB of RAM and 4GB of swap is insanely high for a headless daemon...

**Comment by Fornax96** [comment]
bitcoind uses more iirc

**Comment by lukechampine** [comment]
This will likely be addressed when we make improvements to the wallet. Still, 512MB of RAM may cause issues since we use multiple mmap'd Bolt databases.

**Comment by pmknutsen** [comment]
I would say 2 & 2 is plenty, even when running the explorer. Which reminds
me: Check the -M switch for siad and disable modules you dont need.
1. jul. 2016 3:49 p.m. skrev "Bitcoin Co. Ltd." notifications@github.com:

**Comment by Fornax96** [comment]
If you really want to run it on a digitalocean droplet you may get away with just setting up 4 GB of swap. But remember that that will make Sia _very slow_. Luckily DO is SSD based so it will still be usable.

https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

**Comment by bitcoincoltd** [comment]
Added a 6GB swap and that works to unlock the wallet (looking at the memory usage 1GB of swap would probably have been enough)

**Comment by Fornax96** [comment]
When you start uploading files it will start using more. 

Back with version 0.5 I added 6 GB of swap too and it still ran out of memory, but that may have improved since then. I have not personally tried to run 1.0 on digitalocean yet

EDIT: Looking at my own siad instance it's using about 2.5 GB, and that is while it's uploading and hosting, so it's definitely better. Adding 3 GB swap would probably have been enough

**Comment by droghio** [comment]
Closing since the issue doesn't really concern the Sia-UI and appears to have a work around.
