### ISSUE TITLE
Infinite Loading Screen on Error

### ISSUE THREAD

**Issue by droghio** [NebulousLabs/Sia-UI#368]
Due to issue https://github.com/NebulousLabs/Nodejs-Sia/issues/32, it is possible that the UI startup sequence pauses indefinitely without indicating an error.

If siad encounters an error on startup, the Sia-UI initialization sequence makes it to [loadingScreen.js#L95](https://github.com/NebulousLabs/Sia-UI/blob/master/js/rendererjs/loadingScreen.js#L95) and then stalls.

**Comment by avahowell** [comment]
Does `showError` get called when this happens?

**Comment by avahowell** [comment]
So I added https://github.com/NebulousLabs/Nodejs-Sia/pull/33, which should fix this.  Note that this does not address the reason for Siad failing to launch, but insures that if a launch does fail it will be reflected (using `showError`) by the UI.  

Further investigation is needed to determine why some users UIs are failing to launch Siad; I suspect it's a combination of data corruption causing an overly long module loading time which gets misinterpreted as a 'hanging load' and other weird edge cases which cause `Siad` to fail to launch immediately (executable permissions? disk failure? launching two UIs at close to the same time?). 

 I'll be refactoring the loading screen and `Nodejs-Sia` this week, writing automated tests to hunt these edge cases.
