### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by loviswater** [NebulousLabs/Sia-UI#37]
etminer@ETminerII:~/Sia/New-Sia-UI$ npm install
|

> v8-profiler@5.2.9 preinstall /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-profiler
> 
> v8-debug@0.5.2 preinstall /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-debug

npm WARN optional dep failed, continuing default-browser-id@1.0.2

> electron-prebuilt@0.30.3 postinstall /home/etminer/Sia/New-Sia-UI/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.30.3-linux-x64.zip
[============================================>] 100.0% of 35.99 MB (4.96 MB/s)
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> bufferutil@1.1.0 install /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.1.0 install /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'

> v8-profiler@5.2.9 install /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.9/node-v14-linux-x64/profiler.node" is installed via remote

> v8-debug@0.5.2 install /home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/home/etminer/Sia/New-Sia-UI/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.2/node-v14-linux-x64/debug.node" is installed via remote
npm WARN prefer global node-inspector@0.12.2 should be installed with -g

> Sia-UI@0.4.0 postinstall /home/etminer/Sia/New-Sia-UI
> npm run sia-repo && npm run sia-master && npm run sia-import
> 
> Sia-UI@0.4.0 sia-repo /home/etminer/Sia/New-Sia-UI
> test -d $GOPATH/src/github.com/NebulousLabs/Sia || go get -u github.com/NebulousLabs/Sia/...

package github.com/NebulousLabs/Sia/...: cannot download, $GOPATH not set. For more details see: go help gopath

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "sia-repo"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! Sia-UI@0.4.0 sia-repo: `test -d $GOPATH/src/github.com/NebulousLabs/Sia || go get -u github.com/NebulousLabs/Sia/...`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Sia-UI@0.4.0 sia-repo script 'test -d $GOPATH/src/github.com/NebulousLabs/Sia || go get -u github.com/NebulousLabs/Sia/...'.
npm ERR! This is most likely a problem with the Sia-UI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     test -d $GOPATH/src/github.com/NebulousLabs/Sia || go get -u github.com/NebulousLabs/Sia/...
npm ERR! You can get their info via:
npm ERR!     npm owner ls Sia-UI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/etminer/Sia/New-Sia-UI/npm-debug.log

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! Sia-UI@0.4.0 postinstall: `npm run sia-repo && npm run sia-master && npm run sia-import`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Sia-UI@0.4.0 postinstall script 'npm run sia-repo && npm run sia-master && npm run sia-import'.
npm ERR! This is most likely a problem with the Sia-UI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run sia-repo && npm run sia-master && npm run sia-import
npm ERR! You can get their info via:
npm ERR!     npm owner ls Sia-UI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/etminer/Sia/New-Sia-UI/npm-debug.log

**Comment by Mingling94** [comment]
Glad you brought this up. For developer purposes, the UI requires the user to have a Go Lang environment set up to build a siad binary from our main repo, Sia. It and the UI are evolving rapidly in order to make our release date of August 15th.

**Comment by DavidVorick** [comment]
Is that mentioned in the developer documentation?

**Comment by Mingling94** [comment]
It's mentioned on the initial readme that one needs a "proper" golang environment. I'm not sure if I repeated that in the plugin tutorial

**Comment by DavidVorick** [comment]
https://github.com/NebulousLabs/New-Sia-UI/blob/master/doc/Developers.md

It's not mentioned at all in Developers.md, nor is it mentioned in the plugin tutorial. Also, the link in the readme doesn't link to documentation explaining how to set up a go environment, it only links to the golang homepage. It also needs to be mentioned that you need go 1.4+ (actually I think it's okay to have 1.3 as well, but I'm not 100% confident about that). Many distros such as Ubuntu are using go versions that are many iterations behind.

https://golang.org/doc/install is probably a better resource to link people to. https://golang.org/doc/install/source is also a good resource, but I don't think most people need to see it.

**Comment by Mingling94** [comment]
I'm updating documentation now, I'll put that it requires 1.4+ (that's what I'm running anyways).
