### ISSUE TITLE
default data directory changes per user, can cause privelege errors if Sia-UI is run first as administrator

### ISSUE THREAD

**Issue by avahowell** [NebulousLabs/Sia-UI#370]
On windows, on first run, if Sia-UI is run as administrator, the default data directory (electron's `userData` path), will be set to `\Windows\System32\...\sia`, since this is the current user (Administrator)'s %APPDATA% path.  This does not occur if the UI is run firstly as a user and then as an administrator, since the path will be loaded from `config.json` in this scenario.

I don't think there's an easy fix for this confusing behavior, other than adding an installer.

**Comment by droghio** [comment]
I cannot reproduce the issue on Windows 8. Running as admin still gives me the correct APPDATA environment variable. Can anyone reproduce the issue?

![capture](https://cloud.githubusercontent.com/assets/3069222/16968796/1015a3e0-4ddf-11e6-9197-e0f3bd774462.PNG)

**Comment by avahowell** [comment]
I can't reproduce it either, closing this issue
