### ISSUE TITLE
No seed and no password

### ISSUE THREAD

**Issue by frankbonnet** [NebulousLabs/Sia-UI#379]
Hello,

In windows 10 the seed and password labels are empty in the create wallet screen from the Sia-UI

![sia](https://cloud.githubusercontent.com/assets/3104471/17082530/2f32ec50-5182-11e6-8a61-7a37e7460768.PNG)

**Comment by lukechampine** [comment]
The random words are your seed (and password). Perhaps the design doesn't make this clear enough.

**Comment by droghio** [comment]
@frankbonnet You're going to want to transfer any coins you had in that wallet to a new one and delete that wallet.
