### ISSUE TITLE
Update developer documentation for the new build process

### ISSUE THREAD

**Issue by cyrozap** [NebulousLabs/Sia-UI#39]
The new process is something along the lines of:
1. `sudo npm install -g grunt-cli`
2. `npm install`
3. `grunt`
4. `grunt run`

**Comment by DavidVorick** [comment]
if it's that simple, there should be a build script or a make file.

**Comment by cyrozap** [comment]
I think we can at least roll the `sudo npm install -g grunt-cli` into the `npm install` step and have the `grunt` and `grunt run` steps become `npm test` and `npm run` steps, but we really can't make it much more simple than that. Plus, we already have a build script (Gruntfile.js).
