### ISSUE TITLE
Sia 1.0.1 | Sia UI v1.0.2 | Mac OSX sierra requires sudo to open.

### ISSUE THREAD

**Issue by imjackofitall** [NebulousLabs/Sia-UI#395]
Getting the following error when opening Sia UI on Mac OSX Sierra:

![screen shot 2016-09-27 at 11 39 08](https://cloud.githubusercontent.com/assets/2267993/18857422/19ff37e6-84a7-11e6-89d6-253621f13663.png)

App runs fine when running sudo Sia-UI.app/Contents/MacOS/Sia-UI

Run a few checks on my end and came up short, is there some sort of permission issue?

**Comment by lukechampine** [comment]
See https://github.com/NebulousLabs/Sia/issues/1441
tl;dr: OSX is invisibly moving the app to a read-only temporary folder because it doesn't trust it. Moving the file to a different location should prevent this behavior.

We might need to put this in a FAQ or something. I think it only happens with the latest OSX release.

**Comment by DavidVorick** [comment]
Is there potentially any OS specific code we can write to prevent this?

**Comment by avahowell** [comment]
IIRC the correct way to prevent this is to enroll in Apple's dev program and sign our release binaries.

**Comment by DavidVorick** [comment]
Well, that's not too terrible once we're further along. I guess we can put it on the 'eventually, but sooner eventually rather than later eventually' list.

**Comment by imjackofitall** [comment]
An easy fix would be to have the dmg open up with the .app and a link to the applications folder there. Would be a lot more effective than just a amendment to the FAQ.

**Comment by DavidVorick** [comment]
Re-opening this issue as there seem to be action items still up for discussion

**Comment by lukechampine** [comment]
Fixed in #578
