### ISSUE TITLE
Old file transfers do not get removed from the File Transfers list

### ISSUE THREAD

**Issue by Fornax96** [NebulousLabs/Sia-UI#402]
The file transfers list shows uploads and downloads that are happening. But when an upload or a download finishes the progress bar does not get removed from the list, instead it lingers around. Since the list is ordered by progress all the completed transfers stay at the top of the list, so you have to scroll down to view the progress of the active transfers.

Uploads should either be removed once they reach a redundancy value of 6.00 or 1.00 (I'd day 6.00, since that counts as 100% uploaded in siad). And downloads should simply be removed once the download is complete.

I've noticed that restarting the UI does remove the completed download progress bars. But it does _not_ remove the completed uploads, they will just stick around forever. As a result the upload queue has just become a complete list of every file in the renter.

EDIT: Tested on version 1.0.3-RC

**Comment by Fornax96** [comment]
I've checked the API and all my uploads do seem to have 100% upload progress. I know there used to be a rounding error there in older versions of sia but it has since been fixed. I don't know what caused the uploads to linger around in my queue for so long, but when I arrived at my PC this morning the upload queue was empty. I left the client running overnight and it had finished all my uploads.

**Comment by avahowell** [comment]
Closing this for now.
