### ISSUE TITLE
Renter screen crashes when trying to upload files without first buying storage

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia-UI#408]
A 3gb upload was already in progress, nearly finished. I tried to upload another large file without first buying extra storage, to see if i would be prompted or whether it would be allowed. It did allow me to go through the process of selecting the file, but then the renter screen went completely black and the UI became unresponsive. I closed the UI and reopened with the same result. The wallet no longer unlocks. 
I can still unlock the wallet and see the files/hosting in an earlier version, but the rented files all show as incomplete uploads. 
I've tried a fresh install of 1.0.3rc but it still will not unlock, just sits for hours on the unlocking message.
I'll leave it like that all day to see if it has unlocked by tonight.

**Comment by Chehands** [comment]
ok i've made a bit of progress with this that may help, just to summarize:
i had already uploaded some files and a folder to the renter, which worked ok.
i had started an upload of 3gb which was in progress, reducing my available storage to 10gb
i then tried to upload a 14gb folder without buying more storage, to see if i would be prompted.
After accepting the folder without prompting, the UI crashed to a black screen and became unresponsive and would not unlock.
I've  deleted the files and folder from the renter and the UI now unlocks and is usable again.
so there seems to be a hole that needs patching around a prompt for extra storage space needed if not enough has been purchased.

**Comment by DavidVorick** [comment]
You mentioned that you uploaded the UI folder, which has lots and lots of files in it. I'm wondering if you ran into issues because either the UI or siad itself was unable to correctly process so many files.

That hunch is pretty easy to test, we should have more information soon.

**Comment by Chehands** [comment]
I've tested it, i've tried to upload a very large folder while another is uploading. This time i have bought enough storage so that is not the issue. The same black screen has appeared, i'll leave it like that and see if it eventually clears. The rest of the gui does seem to be working, just the renter has crashed.

**Comment by Chehands** [comment]
I can see through the terminal that the renter is still working and uploading the first folder, so although the renter screen is black it is still working. Hopefully when the first folder finishes uploading it will clear and start the next one.

**Comment by lukechampine** [comment]
@johnathanhowell perhaps the UI is blocking somewhere (an API call?) and never reaching the render code?

**Comment by Chehands** [comment]
Update: when the first folder finished uploading, the screen still remains black. I restarted the UI and the wallet will not unlock, the renter/host do not show any files. The only way to get it working again is to delete all uploaded folders in the renter file. Single uploaded files do not affect it however, only folders. It may be a problem with folder uploads rather than files?
I've started uploading another big single file, and then added another one to the queue without the black screen crash, so it does seem to be folder related, or maybe just the volume of files within the folders.
Nope not volume related, i just added another 3800 single files and its coping well...

**Comment by DavidVorick** [comment]
We have so far been unable to reproduce the problem.

Maybe there's a deadlock that's triggering somewhere in the renter? That would the UI to block. I agree with @lukechampine the next step is to figure out if there's something that can cause the UI to fail to hit the rendering part of the code.

**Comment by avahowell** [comment]
This was fixed with https://github.com/NebulousLabs/Nodejs-Sia/pull/37. @Chehands, please re-open this issue if you encounter this problem again.
