### ISSUE TITLE
Travis CI failing tests that can't download atom-shell

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#41]
Github's API is limiting our travis CI server (rightfully) because we keep downloading atom-shell over and over on the server.

Any suggestions on how to fix?

**Comment by seveibar** [comment]
It's not actually necessary that we download atom-shell for testing, so maybe we could just skip that on travis-ci

**Comment by cyrozap** [comment]
We can make a separate `grunt travis` task that skips that step. This should have the added bonus of speeding up the build.

**Comment by seveibar** [comment]
+1 that's a good idea

**Comment by cyrozap** [comment]
This was fixed by pull request #48.
