### ISSUE TITLE
When the terminal screen is maximised, please move the question mark so it doesn't interfere with the scroll bar.

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia-UI#412]

**Comment by Chehands** [comment]
Just a small issue i know, but its a pain.

**Comment by pmknutsen** [comment]
You mean the scrollbar?

Also, it took me a while to figure out that clicking on the question mark minimizes "Available Commands". Replacing the question mark with a down-arrow when "Available Commands" is displayed would be a strong cue.

**Comment by Chehands** [comment]
Yes, the scroll bar
