### ISSUE TITLE
UI is fixed height

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#42]
It looks silly on my screen.

Also a problem for small screens.

**Comment by seveibar** [comment]
When you minimize the developer console it should be a fixed height - do you mean the ui is scrollable?

**Comment by DavidVorick** [comment]
no it's an exact number of pixels tall, if I try to fullscreen it the bottom half of my screen is blank.

**Comment by seveibar** [comment]
Ahh I see yea that's definitely a bug

**Comment by cyrozap** [comment]
It's happening primarily because a lot of elements have large fixed heights (usually >600). I'm not 100% sure how to fix this, but after looking at the problem for a little bit it's clear the CSS will need to have a lot of work done to it.
