### ISSUE TITLE
When buying storage, if the UI window is not maximised,  the 'allowance' box interferes with the 'accept' and 'cancel' buttons

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia-UI#425]

**Comment by DavidVorick** [comment]
What is the resolution of your screen? I forget what our minimum recommended resolution is, but I think it's at least 1000 pixels wide, which would be half the width of a 1080p screen, or about 75% of a 720p screen.

**Comment by avahowell** [comment]
Fixed in #433
