### ISSUE TITLE
There doesn't seem to be any way to clear the '1 file selected' info on the renter screen if i select the wrong file for download.

### ISSUE THREAD

**Issue by Chehands** [NebulousLabs/Sia-UI#435]
Also, no obvious way of selecting multiple downloads.

**Comment by avahowell** [comment]
You cannot currently select downloads. File selections can be cleared by pressing `Escape`.

**Comment by Chehands** [comment]
Ok thanks, will it be something you will add at some point?

**Comment by avahowell** [comment]
What's the motivation of wanting to select downloads?

**Comment by avahowell** [comment]
Closing this since the main thrust of the issue, clearing selected files, has been resolved.
