### ISSUE TITLE
rounding/graphical problem in host plugin

### ISSUE THREAD

**Issue by nebulousmediacenter** [NebulousLabs/Sia-UI#437]
screenshot should explain everything
![graphical glitch](https://cloud.githubusercontent.com/assets/22984238/19603765/4f0ba866-9780-11e6-8dff-805e88f0d4b4.png)

**Comment by nebulousmediacenter** [comment]
Should probably be rounded to the nearest GB as well

**Comment by avahowell** [comment]
This is a duplicate of #426

**Comment by DavidVorick** [comment]
ah my mistake, closing

**Comment by DavidVorick** [comment]
err, uh, @nebulousmediacenter is me from our house/community machine
