### ISSUE TITLE
Log siad stdout + stderr to a file in UI

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#448]
Each stdout and stderr should live in a separate file. Each time the UI starts siad, it should append a startup message to the logs to clearly indicate separate instantiations. If siad is already running when the UI is started, the UI will not touch these logs nor redirect the output.

These files should probably live in Sia-UI/logs/

**Comment by avahowell** [comment]
Should these logs exist in the data directory, or in the directory that contains the Sia-UI binary?

**Comment by DavidVorick** [comment]
logs should persist if you replace the UI

**Comment by lukechampine** [comment]
Would also be nice to be able to see stdout/stderr output in the UI (maybe a panel in the Terminal plugin?)
EDIT: ah, I didn't see #449

**Comment by avahowell** [comment]
This has been implemented here: https://github.com/NebulousLabs/Nodejs-Sia/pull/38. Closing for now.
