### ISSUE TITLE
LTS branch for the UI

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#487]
Right now there's no LTS branch for the UI, but we need to make one because:

1. Significant bugs have been fixed since the release of lts-v1.0.4

2. There are some allowance updates that add api calls which the UI will start using. Those API calls will not be available in siad v1.0.5-lts, meaning that the lts-v1.0.5 for the UI cannot be dependent on them, but the v1.1.0 UI definitely should be using them (as they will allow for much more accurate allowance balance reporting).

Any time that a bug is fixed which can be fixed both in LTS and in master, that commit should be PR'd into both branches - so long as the bugfix is well tested and has little chance of introducing other bugs, and doesn't also add some feature.

**Comment by avahowell** [comment]
Acknowledged, LTS branch has been created. #495 is the first change that will not be in both branches. Closing this issue
