### ISSUE TITLE
Sia release signatures do not appear to be valid gpg signatures...?

### ISSUE THREAD

**Issue by taoeffect** [NebulousLabs/Sia-UI#525]
From: https://github.com/NebulousLabs/Sia-UI/releases/tag/v1.1.1

How do I verify these files?

```
Sia-UI-v1.1.1-osx-x64.zip
Sia-UI-v1.1.1-osx-x64.zip.sig 
```

I've tried a variety of `gpg --verify` attempts, and none work.

**Comment by lukechampine** [comment]
The signatures can be verified with OpenSSL:
```
openssl dgst -sha256 -verify sia.pem -signature Sia-UI-v1.1.1-osx-x64.zip.sig Sia-UI-v1.1.1-osx-x64.zip
```
The sia.pem data is available [here](https://github.com/NebulousLabs/Sia/blob/3dc47979a53744f5a32c8f3fb355006455d81ac0/api/daemon.go#L75).

**Comment by DavidVorick** [comment]
Closing this issue. Feel free to reopen the issue if you still cannot get the signatures to verify, or otherwise feel there is room for improvement in our process.
