### ISSUE TITLE
missing siad -> many api error notifications

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#53]
if siad is not running, but the UI is running , the UI produces a heavy stream of api error notifications.

this is not optimal

**Comment by Mingling94** [comment]
This stream should stop after a few seconds when the process throws an 'exit' or 'close' signal. Does it just keep going on your computer?

**Comment by Mingling94** [comment]
I see that it seems in some cases those signals aren't thrown. Annoying, but I'll PR a workaround.

**Comment by DavidVorick** [comment]
a lot of people (myself included) will prefer to run siad separately from the ui.
