### ISSUE TITLE
Error alert after click "Show Sia'

### ISSUE THREAD

**Issue by tlightsky** [NebulousLabs/Sia-UI#533]
![image](https://cloud.githubusercontent.com/assets/429211/24574386/38f839d6-16c4-11e7-8ce8-bf355580f5a7.png)

"Hide Sia" & "Quit Sia" would also show this alert

**Comment by bogdanteodoru** [comment]
Hi @tlightsky. Couldn't reproduce this on a Windows 10. What operating system are you using? From the screenshot seems to be Windows 10 as well. Can you remember the steps you did before you got this error? Thank you.

**Comment by tlightsky** [comment]
@bogdanteodoru no, just after a long running, i have not met this since either, i'll close it until i meet this problem again
