### ISSUE TITLE
Logs plugin sorting

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia-UI#536]
v1.2.0-RC1, Win10: The error messages in the Siad tab are somehow sorted, so that similar lines stick together:

![logs_sorting](https://cloud.githubusercontent.com/assets/20227362/24691601/be8248e0-19d4-11e7-8906-f76a1cd6e5a7.png)

Also, i cannot see anything in the Renter and Miner tabs, they are just empty (i think i had this issue before already...)

**Comment by leon54** [comment]
Good morning. I do not have a computer on the Internet. I can not turn on
the week. Thank you for asking me about it.

4 Апр 2017 г. 18:54 пользователь "betaboot" <notifications@github.com>
написал:
