### ISSUE TITLE
Recover Seed window

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia-UI#537]
More padding please :)

Also, could you switch the order of the buttons? Other actions like 'Send Siacoin' have the Cancel button on the left side.

![recover_seed](https://cloud.githubusercontent.com/assets/20227362/24691765/bc1bac4e-19d5-11e7-9dcb-e22bcd7ce01d.png)

**Comment by betaboot** [comment]
Hmmm, but then there is the 'Create Allowance' window where Cancel is on the right side again.

**Comment by DavidVorick** [comment]
We should definitely be consistent about which side we put the cancel button on.

**Comment by avahowell** [comment]
Agreed. Unfortunately the standard side changes based on the platform, on windows the standard is [OK/Recover/Etc][Cancel], whereas on OSX it is [Cancel] [OK]. I would be okay with just standardizing on having Confirm before Cancel in every case, since most of our users are running Windows.

**Comment by DavidVorick** [comment]
That sounds good to me. Don't know if it's easy to make it os-specific, but that's an option too.

Does linux have a standard? Does linux even have popup windows? :P
