### ISSUE TITLE
Host storage folders reordering

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia-UI#549]
This is the same as Sia issue #1668: https://github.com/NebulousLabs/Sia/issues/1668

In siac it's fixed now but not yet in the UI.

**Comment by lukechampine** [comment]
@DavidVorick should we just sort server-side instead?

**Comment by avahowell** [comment]
Sorting seems like something we should be doing in the clients, since it's primarily a presentation thing

**Comment by avahowell** [comment]
That said, we should probably document the fact that the folders are unsorted.
