### ISSUE TITLE
Host storage folders still reordering

### ISSUE THREAD

**Issue by betaboot** [NebulousLabs/Sia-UI#554]
v1.2.0-RC3

Me again :)
Storage folders are now sorted by size, but i have two folders with the same size and so they would still swap places from time to time. Could the list be sorted by name (i think siac is doing that)?

**Comment by DavidVorick** [comment]
+1 to sorting by name in the UI.

@lukechampine should it just be sorted API-side?

**Comment by lukechampine** [comment]
I'm leaning towards yes. In general the API client probably shouldn't make assumptions about the order of such responses, but this seems like an obvious thing that pretty much everyone would want, and doesn't add much overhead.
