### ISSUE TITLE
Unable to compile from sources

### ISSUE THREAD

**Issue by Polve** [NebulousLabs/Sia-UI#575]
npm install gives this error:
[...]

> > electron@1.6.6 postinstall /mnt/disk2/Temp/PublicProjects/Sia-UI/node_modules/electron
> > node install.js
>
> /mnt/disk2/Temp/PublicProjects/Sia-UI/node_modules/electron/install.js:47
>  throw err
>  ^
>
> Error: ENOENT: no such file or directory, lstat '/mnt/disk2/Temp/PublicProjects/Sia-UI/node_modules/electron/dist/resources'
>    at Error (native)

node version is latest LTS (v6.10.2) and npm version is 4.5.0

**Comment by Polve** [comment]
The problem seems to be with the installing of electron itself and not with sia-ui though.
I've tried also with npm v3 with the same problem.
If you have a workaround for this problem I would be happy, otherwise feel free to close this bug report.

**Comment by Polve** [comment]
Today electron installs fine, go figure.
Sorry for the noise...

**Comment by lukechampine** [comment]
Such is life in the JavaScript ecosystem :sob:
