### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#58]
What is the process for creating release binaries that can be distributed to non-developers?

**Comment by seveibar** [comment]
We have to use the [sia packager](https://github.com/seveibar/sia-packager). There are some issues regarding the new build process that need to be hashed out but after than it _should_ be ready to go.

**Comment by DavidVorick** [comment]
I want to make this the top issue for the time being. The release should be very smooth for users. At this point, it doesn't need to be installed anywhere, you should just be able to run it from a folder. Ideally the name would be 'Sia', but if there's only one executable it can be named 'atom' or whatever. There should also be a readme, but nothing else.

The folder structure should have siad in it somewhere. The atom binary should use _that_ siad, and not any other siad.

There shouldn't be any unnecessary files in the download. Currently the download is littered with files that don't do anything and just weren't cleaned up from testing and development. The Windows release has modules folders in at least 2 places, and comes with something like 4 private keys that are shared between all windows users. :(

Checklist form:

- [ ] Only 1 executable + README at the top level. The other stuff (like LICENSE and API.md) should be in a different folder (perhaps 'documentation').

- [ ] Use the siad that comes with the release, and not any other siad on the system. This also holds if you make an installer. Particularly because developers are going to be running multiple versions of siad and users might have screwy configurations.

- [ ] Clean out the unneeded files

**Comment by Mingling94** [comment]
@DavidVorick is this still a thing? How can I help :3

**Comment by lukechampine** [comment]
Our packaging is much better now.
