### ISSUE TITLE
Balance 0 after "Load Seed" (1.2.1 OSX).  Sweeping to another wallet works though.

### ISSUE THREAD

**Issue by jpgallo** [NebulousLabs/Sia-UI#583]
I just installed Sia-UI 1.2.1 OS-X (Sierra) to prepare sending my balance to an offline wallet and....

I can't seem to restore a wallet and have the balance show with my seed.  Tried various fixes I read about described below to no avail.  However, creating a new wallet and sweeping the seed into a new wallet (via "Recover Seed" in the wallet tab).

 To troubleshoot the load seed:

- for all tests blockchain was synchronized (according to the UI).
- deleted the wallet directory and tried loading the seed again from the Wallet tab.
- killed siad in the activity monitor and restarted it in the wallet tab in the Sia-UI
- deleted Sia-UI completely (files in application support + the app itself), resynced blockchain and loaded seed again (still 0).

none of those were able to show my balance from restored seed. as mentioned though I was able to create a new wallet and click "recover seed" and sweep my old balance into the new wallet.

please help, would like to get load seed working to get some trust going with the Sia wallet

**Comment by jpgallo** [comment]
on the Sia forum (https://forum.sia.tech/topic/1001/load-wallet-no-balance-showing-v-1-2-1-osx/3) someone pointed me to this issue (https://github.com/NebulousLabs/Sia-UI/issues/581 )

I wrote:

-------

I saw this thread. Not entirely the same. Similar.

I send from polo and the balance -does- show up
I delete the wallet to test restoring my seed
I can't get the balance back after restoring -- even after reinstalling sia completely...(yes was synced)

**Comment by lukechampine** [comment]
Can you check your wallet.log for errors? You can view the log by pressing `Ctrl+Shift+L` and viewing the wallet tab.

**Comment by jpgallo** [comment]
This was my latest attempt, no errors.  Previous attempts had the found key index start from 1 going to 2 etc.  I looked at the error log before and didn't errors (before my reinstall).

2017/05/07 18:14:15.690353 encrypt.go:426: INFO: Unlocking wallet.
2017/05/07 18:16:59.723380 encrypt.go:383: INFO: found key index 0 in blockchain. Setting primary seed progress to 1
2017/05/07 22:04:08.932640 persist.go:92: STARTUP: Logging has started.
2017/05/07 22:04:22.518529 encrypt.go:426: INFO: Unlocking wallet.

**Comment by lukechampine** [comment]
Please try running the tool I posted in #581 and see if it turns up a larger seed index.

**Comment by jpgallo** [comment]
ok, that fixed it.  thanks.  I did:

$ ./recover scan
Seed: 
Generating keys... Finished in 0.00 seconds.
Scanning blockchain...
Scanned to height 102425 (largest index seen: 0)
Finished scanning. Largest index found: 0
Suggested seed progress: 1

Then

$ ./recover set 1
Rewrote seed progress from 0 -> 1
The next time you unlock the wallet, it will need to do a full rescan.

**Comment by lukechampine** [comment]
Ah, that version had a bug in it actually (you can tell since it generated 100k keys in 0 seconds -- should take 3-10 seconds). Seems like it worked anyway, but might be worth running it again just in case it turns up a higher index. I've updated the download links.
