### ISSUE TITLE
I lost all coins

### ISSUE THREAD

**Issue by duyvu1311** [NebulousLabs/Sia-UI#606]
When creating wallet, I have backed up my SEED. My computer crashed, now I re-install Windows and run Sia Wallet (v.1.2.1) again. I restore my wallet with the back up SEED but my balance is 0.
Here is 2 deposit transactions to my wallet:
8987aa0eb2874e641960e513a88936f60273248e7d9cb7dc1bf1f5d463f840d5
8ae7a76574fddb820a54310a3a001c4bc6a057d2e94b88b53c3faedb3451238d

Please, help me.
Thank you!

**Comment by lukechampine** [comment]
Try using the tool described here: https://github.com/NebulousLabs/Sia-UI/issues/581#issuecomment-299747969

**Comment by duyvu1311** [comment]
I used that tool before posting this issue.
Run:
`recover-windows.exe scan`
Throw error:
`bolt.Close(): funlock error: The segment is already unlocked.`
`error opening consensus database: timeout`

**Comment by lukechampine** [comment]
you need to stop Sia before running the tool.

**Comment by duyvu1311** [comment]
Here is steps:
- Shutdown Sia-UI.
- Run:
`recover-windows scan`
`Seed:`
`Generating keys... Finished in 8.11 seconds.`
`Scanning blockchain...`
`Scanned to height 104357 (largest index seen: 2)`
`Finished scanning. Largest index found: 2`
`Suggested seed progress: 3`

- Run:
`checkaddr 6b557ae202efc02a8421810214226bc67f8777b70592238667548450f16c25ebe5940325e9a8`
`Seed: `
`Generating keys...`
`6b557ae202efc02a8421810214226bc67f8777b70592238667548450f16c25ebe5940325e9a8`
`Found address at seed index 2`

- Run:
`recover-windows set 3`
`Rewrote seed progress from 7 -> 3`
`The next time you unlock the wallet, it will need to do a full rescan.`

- Run Sia-Ui again. My wallet is unlocking. I will show the result when it finishes. Thanks!

**Comment by duyvu1311** [comment]
Great! My coins are back! Thank you very much!
