### ISSUE TITLE
npm build command

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#61]
To build releases we need to have an `npm build` command that does everything but actually runs `atom-shell`.

**Comment by cyrozap** [comment]
`npm test` currently does this (since we don't have any tests); do we need a separate command? Also, it would be `npm run build` because `npm build` is not built-in.

**Comment by seveibar** [comment]
is there a built-in for some kind of build? It's not really appropriate to build a project with either `npm test` or `npm start`- it's not a huge deal if we have to manually call grunt as this only needs to be done on the packager.
