### ISSUE TITLE
macOS Sierra 10.12.4 (16E195) - error

### ISSUE THREAD

**Issue by alekseyivanovbiz** [NebulousLabs/Sia-UI#611]
When an app SIA is opened, an error occurs
<img width="283" alt="sia error" src="https://cloud.githubusercontent.com/assets/28832471/26280259/910b8332-3ddc-11e7-9f4b-c42c4f0d88e1.png">

**Comment by bogdanteodoru** [comment]
@moneymakersbz, please move the Sia application in the Applications folder and try again. This is something related to permissions.

**Comment by alekseyivanovbiz** [comment]
The same thing happens
![sia error](https://cloud.githubusercontent.com/assets/28832471/26283178/9d043b96-3e33-11e7-96a9-53b3b329fa98.png)

**Comment by bogdanteodoru** [comment]
@moneymakersbz, please move only the application itself. Not the whole folder. Only the "Sia-UI" file.

**Comment by alekseyivanovbiz** [comment]
Thank you!!! 
![sia](https://cloud.githubusercontent.com/assets/28832471/26284332/7353a532-3e49-11e7-90ab-0d2435d45869.png)
