### ISSUE TITLE
Unable to recover seed - funds lost

### ISSUE THREAD

**Issue by Wags56** [NebulousLabs/Sia-UI#612]
Sorry if this has been addressed before, but I'm somewhat of a noob here with Sia.

Computer reformatted and Sia installed on Windows 10.
New wallet seed created and sync allowed to proceed.
Did a recover seed and now get:
Sia-UI Wallet Error
error when calling/wallet/sweep/seed: transaction fee exceeds value of swept outputs

I sent some Sia to this address via Poloniex:
be724f5aea918768e92c31d33e9ca8ebbf53dc0fe338309c806ceae239123f1650aba103ef29

Yes, that is the address that is associated with the seed.

Any ideas?

**Comment by Wags56** [comment]
Update:
Did a check using http://explore.sia.tech/ and the above address.  Though Poloniex has it listed as a successful transaction, I don't see that address as having received the required amount.

Ticket put into Poloniex.  Will see what they say.

**Comment by Wags56** [comment]
While waiting for responses, I completely removed the Sia 1.2.1 folder and the files located at C:\users\myname\AppData\Roaming\Sia-UI.
I unpacked a new folder from the ZIP file and once again synchronized.
I stopped and restarted Sia UI
I created a new wallet with a new seed
I ran recover seed from the GUI and once again got the same error:
-----------------------------
Sia-UI Wallet Error
error when calling/wallet/sweep/seed: transaction fee exceeds value of swept outputs
-----------------------------
I now get this error when I try to recover any of my past seeds.

Ideas?  Anyone?

**Comment by lukechampine** [comment]
Sweeping means transferring all the funds from one wallet to another. This incurs a transaction fee. The error message is saying that the seed has less money in it than the cost of sending it to your new wallet.

Generally you should create the wallet using the existing seed instead instead of sweeping into a new seed.

**Comment by Wags56** [comment]
Thanks!  Will give that a try next.  Still, if there are no funds to send to my new wallet, that means that the transfer must not have worked.

**Comment by Wags56** [comment]
Ran a clean install of Sia and synch to blockchain.  Created the wallet using the existing seed, but nothing in it.

A question please:  
If I have "swept" an old seed into a new seed, do the hash addresses from the old seed get permanently transferred to the new seed or do they remain associated with the old seed?  Should I be able to see that previous address using a "wallet addresses" command?

**Comment by avahowell** [comment]
1.2.1 has an issue loading seeds correctly, please download 1.2.2, clear your wallet, and try again: https://github.com/NebulousLabs/Sia-UI/releases/tag/v1.2.2

When you "seep" into a new seed, all of the money in the old seed gets transferred to the new one. Any addresses associated with the old seed will still go to the old seed.

**Comment by Wags56** [comment]
Many thanks in advance.  Will post results when I sync and load the old seed.

**Comment by Wags56** [comment]
Well, 1.2.2 works much better and shows a lot of transactions.  In fact, it seems like there are more transactions there than I actually made!

My other known transactions are indeed listed with the exception of the one that contained the deposit from Poloniex.  A "Wallet Addresses" on the terminal line lists a lot of addresses I didn't even know were associated with this account, but does include the one in question.

Not sure what to do next.  Ticket put into Poloniex, but no response from them.  May need to check it all up to experience on this one.

**Comment by Wags56** [comment]
I suspect that all of the other transactions (debits) were secondary to trying to store a file.  All of them (I believe) occurred on the same day.  Still waiting for Poloniex to respond.  Seems like they're looking into it since that part of my account is locked.

**Comment by Wags56** [comment]
While waiting for Poloniex to respond, I've got a miner PC working on Sia to deliver to the above address.  I figure that if the mined coins are delivered, the problem lies with Poloniex.  If not, then the problem is on the Sia side.  ETA to delivery is about 3 days.  Perhaps this will shed a bit of light on the problem.

**Comment by Wags56** [comment]
Confirmed.  I believe that the problem is with Poloniex.  My miner deposited 5011 SC into be724f5aea918768e92c31d33e9ca8ebbf53dc0fe338309c806ceae239123f1650aba103ef29 which can be verified using http://explore.sia.tech/

Will let you know what they say.

**Comment by Wags56** [comment]
Just had another deposit in the same account from my miner.  The account number is working fine.  Still no record of a deposit from Poloniex.  Still no response from them.

**Comment by DcyMatrix** [comment]
don't mine directly to an exchange! I think Poloniex has that mentioned
somewhere as well. Hope you get it sorted out though :-)

**Comment by Wags56** [comment]
Not mining directly to Poloniex. Mining to Sia wallet and checking for deposits there.  Problem was a transfer from Poloniex to Sia wallet using the above address.  The Sia wallet address works fine when mining is sent to it. The address didn't work when transferring Poloniex exchange Sia to the same address.

**Comment by Wags56** [comment]
Final follow up:
I was out of town for a bit, but when I returned and restarted my Sia wallet and it finished synching, the funds from Poloniex were there.  Mind you, this is about 20 days later.

I have heard nothing from them regarding the issue and cannot explain why it might have taken so long to move from their account to my account.

If any Sia representative is interested, the txid is 5f89dfe73379063616ece48c03c3bc0db1e7a9dc7aeccac8aa5d077018b0c366

If anyone has any insight, I'd be interested to hear it.  Will keep this thread open for a couple more days to see if there are any thoughts.  After that, I'll close it out.

**Comment by lukechampine** [comment]
Poloniex was experiencing withdrawal problems for a while. We helped them resolve the issue. I assume they are now clearing out a large backlog of orders. See: https://blog.sia.tech/growing-pains-8e7b01c56f7e

**Comment by Wags56** [comment]
Thank you for the explanation.  Growing pains are good, they make for a better product in the long run.  Keep up the great work!
