### ISSUE TITLE
Fancier UI

### ISSUE THREAD

**Issue by KeizerDev** [NebulousLabs/Sia-UI#618]
How about making things look nicer? What about this kind of style? https://dribbble.com/shots/3176964-File-Manager-Dashboard

If I get some thoughts I can recreate the UI a bit, so it looks more Premium

**Comment by alexfreska** [comment]
I was recently using the UI and had a similar thought. I seem to remember reading sia was going to work on general branding in the near future.. I'd imagine it would be most productive to coordinate any work on the UI design with any new branding.

**Comment by DavidVorick** [comment]
We are contracting professional help to work on our branding. This includes both the website and the UI, and some other features of our business. It may take a few months for this to pay off, but expect to see some design upgrades soon across the board.

**Comment by KeizerDev** [comment]
Cool man! Keep up the good work :)

**Comment by adiled** [comment]
I am a UI dev, willing to contribute

**Comment by pdroalves** [comment]
Please!

**Comment by apertamono** [comment]
I'd rather have a user-friendly design than a flashy design. The current UI is pretty good in this respect: it uses clear, big icons with text for navigation and the main options. Some of the text could use a little more contrast. The Dribble example shown here is fashionable, but contains navigation icons without text and low-contrast check boxes.

**Comment by adiled** [comment]
@ProkhorZ You can't tell a design's usability without the experience. So labeling a good UI as flashy is unfair to the designer. It's only part of the picture till there are interaction animations or a usable prototype available for judgments.

**Comment by apertamono** [comment]
@m-adilshaikh I thought it was just an example? I'm discussing priorities, not a specific design.

**Comment by KeizerDev** [comment]
@ProkhorZ It was indeed just an example, that dribbble design

**Comment by tbenz9** [comment]
The UI has been refreshed in 1.3.1 and will continue to be iterated on.  I suggest we close this issue.
