### ISSUE TITLE
New Wallet Creation: Seed and automatic password are the same 

### ISSUE THREAD

**Issue by aaronjolson** [NebulousLabs/Sia-UI#621]
I recently tried to make a new wallet. I did not select the custom password option. When prompted to copy the seed and password, The two fields were the exact same.
I backed out and made a wallet using a password of my own devising. 
I am running windows 10.  Running Sia-UI-v1.2.2-win32-x64

**Comment by lukechampine** [comment]
This is expected behavior. The seed is also a cryptographically strong password, much stronger than what a user would typically provide themselves.

Perhaps we could make the UX a little clearer here. Open to suggestions.

**Comment by Voniram** [comment]
Hi there,
I have the same issue. My seed and password are the same and I cannot confirm it to continue.
I am using Win10 and the version is Sia-UI-v1.3.1-win32-x64.
