### ISSUE TITLE
Change "Receive Siacoin" button to display the most recently generated address

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia-UI#628]
I'm not sure if the UI devs follow the [/r/siacoin subreddit](https://www.reddit.com/r/siacoin/) actively, but probably the most common source of confusion for new users is the "Receive Siacoin" button in Sia-UI. Users not familiar with cryptocurrencies don't understand why the address is changing each time and some of them panic because they sent SC to the address shown and now they're seeing a totally different address.

Here are a few examples from just the last three weeks:

* [Why is the sia wallet address different each time?](https://www.reddit.com/r/siacoin/comments/6c5u3r/why_is_the_sia_wallet_address_different_each_time/)
* [Wallet address?](https://www.reddit.com/r/siacoin/comments/6etn6l/wallet_address/?st=j3qhq1qy&sh=b22842e1)
* [Does the wallet address change while syncing for the first time?](https://www.reddit.com/r/siacoin/comments/6c0fzm/does_the_wallet_address_change_while_syncing_for/?st=j3qhqeok&sh=a6184c0b)
* [[Help] Sent SC to the wrong address](https://www.reddit.com/r/siacoin/comments/6gb6dd/help_sent_sc_to_the_wrong_address/?st=j3qhqivz&sh=253e148b)
* [Sia-UI address constantly changing?](https://www.reddit.com/r/siacoin/comments/6eaoe1/siaui_address_constantly_changing/?st=j3qhqlu8&sh=a3df71d3)
* [Question about how SiaCoins Wallet works](https://www.reddit.com/r/siacoin/comments/6ewm1r/question_about_how_siacoins_wallet_works/?st=j3qhz6w5&sh=7a78e27a)
* ["Receive Siacoin" Addresses](https://www.reddit.com/r/siacoin/comments/6le1c4/receive_siacoin_addresses/)

Proposal: "Receive Siacoin" displays the most recently generated address. The user can still generate new addresses by going to the Terminal, but it eliminates a major source of confusion for new users.

Long term, I think there are ways to convey to the users that they have many addresses and can generate new ones on demand, but I hope this proposal is a reasonable short term solution.

**Comment by lukechampine** [comment]
We explicitly avoid address reuse for security reasons. I definitely agree that this could be made more clear though. Perhaps the popup could show a list of the user's addresses, along with a "New Address" button. Then the user can opt to generate a new address or reuse an existing address.

**Comment by mtlynch** [comment]
>We explicitly avoid address reuse for security reasons.

I get the privacy concern, but what's the security concern?

**Comment by lukechampine** [comment]
Ah, I was conflating them I guess. It is a privacy thing.
However, privacy isn't a primary goal of Sia, so it may be ok to sacrifice some privacy for user-friendliness. For example, given the option, I doubt that most users would choose to generate a new address for every transaction. But if organizing it that way makes the software easier to use, it may be an acceptable trade-off.

**Comment by mtlynch** [comment]
The [last comment](https://github.com/NebulousLabs/Sia-UI/issues/628#issuecomment-307531411) seemed like this was under consideration for a fix, but there's been no movement since.

We've had two more posts to /r/siacoin in two days from users who got confused about this:

* ["Receive Siacoin" Addresses](https://www.reddit.com/r/siacoin/comments/6le1c4/receive_siacoin_addresses/)
* [Siacoin receive address different than mining address?](https://www.reddit.com/r/siacoin/comments/6lr7w7/siacoin_receive_address_different_than_mining/)

I even get [confused comments](https://mtlynch.io/windows-sia-mining/#comment-3377788206) on my mining guide even though the guide explicitly warns about the changing addresses.

This is the most common source of user confusion I see with Sia. It would be great to see this get prioritized for fixing.

**Comment by mtlynch** [comment]
>i put the exact address provided in the Siacoin wallet. its been hours and my coins are not here. **i realized the receive siacoin address changes evreytime i click on that**...did i lose my SC?...

https://www.reddit.com/r/siacoin/comments/6m8600/sent_sc_from_bittrex_to_sc_wallet/

**Comment by lukechampine** [comment]
The current API doesn't provide an easy way to see what the most recently-generated address is. There's a route that returns all the addresses, but they are sorted lexicographically.

Maybe we could change the button to "generate new address" and add a new button to show the list of all addresses. That gives users the option to reuse an address from the list if so desired.
The downside is that siad generates a fair number of addresses without user prompting, so the presence of these "internal" addresses could be confusing to a new user.

**Comment by mtlynch** [comment]
>Maybe we could change the button to "generate new address" and add a new button to show the list of all addresses.

Is it possible for the UI to cache a single address from the list as the default payment address? Like persist it in a settings/preferences file?

**Comment by avahowell** [comment]
@mtlynch the fix for this is being developed here: https://github.com/NebulousLabs/Sia-UI/pull/694.
