### ISSUE TITLE
Download via file picker

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#63]
I'm not sure where the downloads are currently going when you download a file from the UI. I haven't been able to find them.

The API call I believe only accepts a fullpath. I think right now the best behavior for the UI when downloading is to ask the user where the file should be put, and then give the daemon a fullpath.

**Comment by seveibar** [comment]
Because we're using atom-shell, we can now access file paths (normally this permission isn't given)

**Comment by DavidVorick** [comment]
can you create a file picker that lets the user choose the directory to download into?

**Comment by seveibar** [comment]
Yupp, for whoever works on this issue, [here's the documentation](https://github.com/atom/atom-shell/blob/master/docs/api/dialog.md) regarding dialogs from atom-shell.
