### ISSUE TITLE
npm install error message

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#63]
"when running npm install on the new ui, it gives warnings about have a newer node version"

`npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})`

**Comment by bitspill** [comment]
That error stems from xmlbuilder@2.2.1 having an overly specific version check which was fixed [here](https://github.com/oozcitak/xmlbuilder-js/commit/b13f9f701885d512dc1a97d8eea81f57630733be) on February 9th 2015, however plist had it's dependency set overly strict as well and used the old xmlbuilder until 17 days ago when it's dependencies were updated [here](https://github.com/TooTallNate/plist.js/commit/42cb709a68307c81a7c6ebe04c9e279f1cde73dc). While they have updated the dependencies on master plist.js has not made a new release (v1.1.0 was released August 27th 2014) and as such the old xmlbuilder is still being pulled.

For reference here's a snippet of the node-inspector dependency tree:

```
ana@hetz1:~$ npm-remote-ls node-inspector
└─ node-inspector@0.12.3
   ├─ biased-opener@0.2.6
   │  ├─ browser-launcher2@0.4.5
   │  │  ├─ plist@1.1.0
   │  │  │  ├─ xmlbuilder@2.2.1
   │  │  │  │  └─ lodash-node@2.4.1
```

**Comment by Mingling94** [comment]
So I think this is fixed then?
