### ISSUE TITLE
Renter view: 'active' vs. 'repairing'

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#64]
Right now, there's not really any indication of whether a file is ready to be downloaded, whether it's actively being uploaded, whether it's actively being downloaded.

This issue is multi-part.

First, I've deprecated the "/renter/status" call, which is what the UI is currently using to populate the view. Instead, you should use "/renter/files", which gives you a multi-part struct containing more information about each file.

In particular, it has the 'Available' field, which indicates if a file is ready to be downloaded. It has the 'Repairing' field, which indicates if whether an upload is in progress (note, a file can be both 'available' and 'repairing' at the same time), and 'TimeRemaining', which indicates how much time is left before a file's contracts expire.

====

At some point in the future I'm also going to add a download queue, which will indicate which files are currently being downloaded and have some metric for progress. 'Repairing' might also deserve some sort of progress related metric but I'm less certain about that because 'repair' can be an ongoing process, and could reset if hosts start going offline.

I'll make a separate issue for the download queue once I've made api calls for it.

**Comment by seveibar** [comment]
What value does showing if a file is repairing add to a user using the application?

**Comment by DavidVorick** [comment]
The file needs to be repaired on occasion, and that can only happen while the thing is running. If a user neglects repairing for too long, the file becomes at risk of being lost.
