### ISSUE TITLE
How  to delete wallet data?(MacOs)

### ISSUE THREAD

**Issue by AFAP** [NebulousLabs/Sia-UI#643]
I want to delete wallet and reload from seed, how can I find the wallet file?I use sia-ui on mac.

**Comment by AFAP** [comment]
Please help me

**Comment by lukechampine** [comment]
in the Terminal view, type `wallet init-seed --force`. You should be prompted for a new seed, which will overwrite your existing wallet.

**Comment by AFAP** [comment]
Thank you very much. My problem has been solved.
When I use Sia-UI on both Mac and Win, the transactions will be inconsistent, so i need to reload my wallet.

**Comment by lukechampine** [comment]
>When I use Sia-UI on both Mac and Win, the transactions will be inconsistent

This is already fixed in the master branch. It will be included in the v1.3.0 release :)
