### ISSUE TITLE
Renter Estimated Fee is extremelly high

### ISSUE THREAD

**Issue by Cinerar** [NebulousLabs/Sia-UI#646]
https://github.com/NebulousLabs/Sia/issues/1930

Here is estimation:
https://github.com/NebulousLabs/Sia-UI/blob/master/plugins/Files/js/components/allowancedialog.js#L16

**Comment by sanasol** [comment]
https://github.com/NebulousLabs/Sia/blob/b174d012a09466d907495203f0d51b261269d9c2/modules/renter/contractor/formcontract.go#L46-L57

Why this is not used for (close to) real extimated fee?
