### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by bent-rasmussen** [NebulousLabs/Sia-UI#657]
Getting a heck of a lot of these errors in Sia-UI (tens of identical dialog popups in a row). CTRL+C => CTRL+V from dialog:

[Window Title]
Error

[Main Instruction]
Sia-UI Files Error

[Content]
ESOCKETTIMEDOUT

[OK]

Not sure what it means or if its somehow specific to my machine or scenarios.

Should I be worried about some files not uploading?

Sia & Sia-UI version = 1.2.2
Update: Windows 10 (Insider Preview)

**Comment by pavelpp** [comment]
I have the same issue on Mac OS with 1.3.0

**Comment by hklkf200553** [comment]
have the same issue

**Comment by contenidosonline** [comment]
same with ubuntu and  Sia UI version: v1.3.0
Sia version: 1.3.0

**Comment by Twitchykid** [comment]
I am having this same issues on ubuntu 14.04 Sia UI version v1.3.0

However, I only started seeing when I tried uploading more than 2 files at once. The size of the 2 files are about 2 and 1 GB each.

**Comment by tbenz9** [comment]
Duplicate of https://github.com/NebulousLabs/Sia/issues/1605
This is one of the most common bugs in Sia, the devs are well aware of it.

Recommendation to devs: Close as duplicate
