### ISSUE TITLE
Sia-UI shouldn't strip whitespace from password

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia-UI#665]
Thanks for the quick response on #662!

I think #663 was actually a bit too aggressive in its fix.

Stripping leading and trailing whitespace from the *seed* is fine, because it's impossible for a seed to have leading or trailing whitespace. We don't want to strip whitespace from the *password* because AFAIK it's legal to have a leading or trailing whitespace character in a password. If the user generated their password with a password manager, they could end up with a leading or trailing space. We don't want Sia-UI to lock out users if they set their password in a previous version or through `siac`.

**Comment by lukechampine** [comment]
Agreed. For example, it's conceivable (though a bit strange) that a password manager could generate a password with leading or trailing whitespace.
My feeling is that the password prompt should warn the user when the password has leading or trailing whitespace, but not prevent them from entering it (or silently strip it off behind the scenes). These warnings should appear both when creating the password and upon subsequent entry.

**Comment by mtlynch** [comment]
Fixed with #667
