### ISSUE TITLE
Sia-UI v.1.3.0-rc7 reports Sia version as 1.2.2

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia-UI#677]
Observed on Win10 x64:

![image](https://user-images.githubusercontent.com/7783288/28443570-e9fffa5e-6d84-11e7-8642-094af7ea1731.png)

I checked the `siad.exe` and `siac.exe` versions that came in the zip and they report 1.3.0. Not sure where it's getting 1.2.2.

**Comment by DuncanAitken** [comment]
Have you got a siac.exe (v. 1.2.2) anywhere on your system?

**Comment by DavidVorick** [comment]
I'm not seeing that on my machine, I think it's likely you have a v1.2.2 daemon running somewhere. The UI will use the existing daemon if it finds one that is running already.

**Comment by mtlynch** [comment]
I have siad 1.2.2 downloaded on that system and I had run it previously, but there are definitely no other siad daemons running when I launch Sia-UI 1.3.0-RC7. Here's the repro:

https://streamable.com/95xzc

**Comment by lukechampine** [comment]
In the stream, `siac version` reports its own version as 1.3.0, and siad's version as 1.2.2. What does `siad version` report?

I checked the Windows binaries bundled with rc7. The filesizes match the ones in your stream exactly, but they each report v1.3.0. Very strange.

**Comment by avahowell** [comment]
I think this is because Sia-UI now re-uses config.json across upgrades, and determines if `siad` needs to be replaced by comparing the last version used as logged in `config.json` with the current version: https://github.com/NebulousLabs/Sia-UI/blob/master/js/mainjs/config.js#L46. Looks like it's not detecting the upgrade correctly, and it's still pointing at an old (v1.2.2) siad.

Did you upgrade straight from v1.2.2 to RC7? Or did you run multiple RCs?

**Comment by mtlynch** [comment]
>In the stream, siac version reports its own version as 1.3.0, and siad's version as 1.2.2. What does siad version report?

```
> siad version
Sia Daemon v1.3.0
```

@johnathanhowell's explanation makes sense.

>Did you upgrade straight from v1.2.2 to RC7? Or did you run multiple RCs?

I went straight from 1.2.2 to RC7.

**Comment by avahowell** [comment]
@mtlynch do you mind posting the contents of `%APPDATA%\Sia-UI\config.json`?

**Comment by mtlynch** [comment]
Sure, here you go: https://gist.github.com/mtlynch/ece44387f2c3f2523968e39bcd60d9d4

**Comment by avahowell** [comment]
Thanks. Fixed in https://github.com/NebulousLabs/Sia-UI/pull/682, in the mean time you can delete `config.json` and restart.
