### ISSUE TITLE
Need prebuilt binaries for release branch

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#7]
Right now, to run the project you must have atom-shell installed, then run it in the project directory.

atom-shell has the build process documented here: https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-distribution.md

**Comment by DavidVorick** [comment]
Do you think we should add the prebuilt binaries to the repo? Or just add them to the folder that we zip and distribute?

**Comment by seveibar** [comment]
They're going to be too many and they'll be too big to add to the repo (i think)- a good approach might be to do what atom-shell does here: https://github.com/atom/atom-shell/releases

I'm trying to get the build process down so I'll have a more exact estimate on the size soon

**Comment by seveibar** [comment]
Looks like the binaries come out to 30-40MB

**Comment by DavidVorick** [comment]
that's not so bad

**Comment by Mingling94** [comment]
Is this still an issue? I'm still fuzzy on the build process
