### ISSUE TITLE
UI is reporting the wrong version

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#70]
As displayed by 0.4.1 GUI:
![2015-09-07_17_53_50-192 168 1 107_360](https://cloud.githubusercontent.com/assets/2316841/9717332/eb2e5b3c-553f-11e5-95e8-35d452907dd3.png)

**Comment by Mingling94** [comment]
Your sia-version is determined by the call to `/daemon/version` from siad, so yours is 0.4.0 when testing. Otherwise, I will update this in a PR.
