### ISSUE TITLE
Download Queue

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#70]
There's a new API call, /renter/downloadqueue, which gives a list of all downloads that have been requested, are in progress, or have finished. I believe API.md documents what each of the values indicates.

The user should have an idea of what downloads are in progress, so that after they click on a file to download it, there's more than a vague notification that it's started working.

**Comment by seveibar** [comment]
I think the best way to solve this is to have the download notification linger with a progress bar, then be optionally dismissed.

**Comment by DavidVorick** [comment]
For the immediate future, there's not going to be a progress bar, but it's something that Luke knows how to implement. We would just add two fields to the downloadqueue responses: `bytesDownloaded` and `bytesTotal`, from which you could derive a %, and potentially a velocity. For the time being though we're working on other things.

If you want to fake a progress bar for the time being, that's fine by me.
