### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by afsarker** [NebulousLabs/Sia-UI#705]

**Comment by lukechampine** [comment]
We provide signed checksums for all downloads: https://github.com/NebulousLabs/Sia-UI/releases/tag/v1.3.0

You can verify the signature by running:
```
openssl dgst -sha256 -verify sia.pem -signature Sia-UI-v1.3.0-win32-x64.zip.sig Sia-UI-v1.3.0-win32-x64.zip
```
where `sia.pem` is the [Sia Developer Key](https://github.com/NebulousLabs/Sia/blob/3dc47979a53744f5a32c8f3fb355006455d81ac0/api/daemon.go#L75).

Antivirus software is susceptible to false positives so I'm not too worried about this.

**Comment by DavidVorick** [comment]
On that note though, if you ever do end up with a Sia download which has an invalid signature, please let us know, and let us know where you got it from. That would be very interesting, and something we would want to solve quickly.

**Comment by asifssarker** [comment]
sure, thanks. Well, but how to be sure that it is a false positive or not?
