### ISSUE TITLE
can not receive sia coin from some trading platform

### ISSUE THREAD

**Issue by kawais** [NebulousLabs/Sia-UI#717]
I send 1sc to my wallet from some trading platform.
The transactions status is comfirmed and I synchronized block, but balance still is 0sc.
[https://imgur.com/hSw0K4j](https://imgur.com/hSw0K4j)

I tried recover-windows.exe
1. run recover-windows
F:\BitCoin\Sia-UI\sia>recover-windows.exe scan
Seed:
Generating keys... Finished in 7.70 seconds.
Scanning blockchain...
Scanned to height 123446 (largest index seen: 1)
Finished scanning. Largest index found: 1
Suggested seed progress: 2

2. set seed progress
F:\BitCoin\Sia-UI\sia>recover-windows.exe set 2
Rewrote seed progress from 2 -> 2
The next time you unlock the wallet, it will need to do a full rescan.

but nothing to help.

**Comment by lukechampine** [comment]
This is because 1 SC is below the "dust threshold:" the cost of spending a 1 SC output (due to transaction fees) is greater than 1 SC. We are working to make this less confusing in the UI. Rest assured that if you send a larger amount, it will appear in your balance.

**Comment by acuestamd** [comment]
please, reconsider taking off from the main GitHub tittle "highly efficient wallet" ... come back at us when u have worked out something w trezor or others
