### ISSUE TITLE
At wits end: Install Sia. Run UI. Sync. Open Wallet. Close Sia. Open Sia. Errors out. Every single time.

### ISSUE THREAD

**Issue by bclaymiles** [NebulousLabs/Sia-UI#721]
Windows 10 Pro 64 bit.
Core i7-7700k, no OC or anything.
32GB ram.
m.2 storage for C:
Sia-UI-v1.3.0-win32-x64.zip

I've "installed" Sia numerous ways. First, not installing at all - just unzip and run the sia-UI from the folder created in the download directory. Or put it on the desktop. Or put it in the Program Files folder. None of those differences seem to matter, which seems reasonable. The necessary files are always automatically deposited in C:\Users\paul\AppData\Roaming\Sia-UI.  I've tried running Sia 'normally' and as Administrator - same failure. I've gone through deleting every trace of Sia and re-downloading the application each time. No difference.
After each successful reinstall, after closing and re-opening, the interface always displays this:

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Closing host...
Closing wallet...
Closing transaction pool...
Closing consensus...
Closing gateway...
invalid argument

Okay, so I dig deeper into the numerous logfiles under AppData. I find the following errors, every time - doesn't matter if run as self or administrator.

**host\contractmanager.log** shows this:
2017/09/23 23:11:07.692110 dependencies.go:200: STARTUP: Logging has started.
2017/09/24 00:49:36.263418 writeaheadlogsync.go:50: SEVERE: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\paul\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\paul\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
2017/09/24 05:07:04.796498 contractmanager.go:150: SHUTDOWN: Logging has terminated.
2017/09/24 05:09:50.957370 dependencies.go:200: STARTUP: Logging has started.
2017/09/24 05:14:45.441917 contractmanager.go:150: SHUTDOWN: Logging has terminated.

**host\host.log:**
2017/09/23 23:11:07.691107 dependencies.go:105: STARTUP: Logging has started.
2017/09/23 23:11:13.960562 upnp.go:131: INFO: successfully forwarded port 9982
2017/09/23 23:11:13.961563 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/23 23:11:21.641807 upnp.go:61: WARN: discovered hostname "0.0.0.0:9982" is invalid: host is the unspecified address
2017/09/23 23:41:21.642270 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/23 23:41:30.073053 upnp.go:61: WARN: discovered hostname "0.0.0.0:9982" is invalid: host is the unspecified address
2017/09/24 00:11:30.073914 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 00:12:05.599819 upnp.go:55: WARN: failed to discover external IP
2017/09/24 00:42:05.600099 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 00:42:32.658034 upnp.go:55: WARN: failed to discover external IP
2017/09/24 01:12:32.658156 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 01:13:17.046992 upnp.go:55: WARN: failed to discover external IP
2017/09/24 01:43:17.047010 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 01:44:03.216753 upnp.go:55: WARN: failed to discover external IP
2017/09/24 02:14:03.216971 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 02:14:49.385698 upnp.go:55: WARN: failed to discover external IP
2017/09/24 02:44:49.386385 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 02:45:41.499827 upnp.go:55: WARN: failed to discover external IP
2017/09/24 03:15:41.500347 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 03:16:13.542501 upnp.go:55: WARN: failed to discover external IP
2017/09/24 03:46:13.542927 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 03:46:59.271200 upnp.go:55: WARN: failed to discover external IP
2017/09/24 04:16:59.271899 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 04:17:20.415457 upnp.go:61: WARN: discovered hostname "0.0.0.0:9982" is invalid: host is the unspecified address
2017/09/24 04:47:20.417187 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 04:47:45.322089 upnp.go:55: WARN: failed to discover external IP
2017/09/24 05:07:04.627044 network.go:214: ERROR: failed to clear port: no UPnP-enabled gateway found
2017/09/24 05:07:04.797000 host.go:252: SHUTDOWN: Logging has terminated.
2017/09/24 05:09:50.956869 dependencies.go:105: STARTUP: Logging has started.
2017/09/24 05:09:50.961381 persist.go:97: WARN: AutoAddress '' loaded from persist is invalid: missing port in address
2017/09/24 05:09:50.961381 persist.go:106: WARN: NetAddress '' loaded from persist is invalid: missing port in address
2017/09/24 05:10:34.233416 upnp.go:122: WARN: could not automatically forward port 9982: no UPnP-enabled gateway found
2017/09/24 05:10:34.233416 network.go:208: ERROR: failed to forward port: no UPnP-enabled gateway found
2017/09/24 05:10:34.233416 upnp.go:43: No manually set net address. Scanning to automatically determine address.
2017/09/24 05:11:31.326291 upnp.go:55: WARN: failed to discover external IP
2017/09/24 05:14:45.442920 host.go:252: SHUTDOWN: Logging has terminated.

**host\contractmanager\contractmanager.log:**
2017/09/23 23:11:07.692110 dependencies.go:200: STARTUP: Logging has started.
2017/09/24 00:49:36.263418 writeaheadlogsync.go:50: SEVERE: ERROR: unable to atomically copy the contract manager settings: rename C:\Users\paul\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json_temp C:\Users\paul\AppData\Roaming\Sia-UI\sia\host\contractmanager\contractmanager.json: Access is denied.
2017/09/24 05:07:04.796498 contractmanager.go:150: SHUTDOWN: Logging has terminated.
2017/09/24 05:09:50.957370 dependencies.go:200: STARTUP: Logging has started.
2017/09/24 05:14:45.441917 contractmanager.go:150: SHUTDOWN: Logging has terminated.
2017/09/24 05:24:10.923170 dependencies.go:200: STARTUP: Logging has started.

but the biggie is the **renter\contractor.log**, which balloons up to dozens of megs after a single restart, repeating the following endlessly:

2017/09/23 23:11:07.714168 contractor.go:178: STARTUP: Logging has started.
2017/09/23 23:13:50.303457 update.go:57: Unable to save while processing a consensus change: rename C:\Users\paul\AppData\Roaming\Sia-UI\sia\renter\contractor.journal_tmp C:\Users\paul\AppData\Roaming\Sia-UI\sia\renter\contractor.journal: Access is denied.
2017/09/23 23:13:50.304961 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.312481 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.313985 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.315990 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.316993 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.318497 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.320001 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.321505 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.323009 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.324012 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.325014 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.344065 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.345569 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.346571 update.go:57: Unable to save while processing a consensus change: invalid argument
2017/09/23 23:13:50.348076 update.go:57: Unable to save while processing a consensus change: invalid argument

(repeat until the logfile is 30 or 40 or 60 megabytes in size)

I have countless applications installed on this machine (along with a dozen or more different cryptocurrency wallets. They all save the tasty bits under AppData\Roaming, just like Sia. They all run fine. 

I've gone through this cycle ...six times? eight times? I've lost count. It always ends up the same, and I can't for the life of me figure out why only Sia gives me this grief. I would really like to get behind Sia and actually use it, but this issue is just pounding me down.  I'm hoping developer eyeballs can explain why this is happening, and what the fix might be.

thanks!

**Comment by lukechampine** [comment]
Hmm. The `rename` operations are failing. Windows errors aren't very helpful, but I think this can happen if another process has the file open. If that were the case, we'd expect to see this error a lot more frequently, but we don't. Do you have any other programs that could be accessing these files? Antivirus maybe?

**Comment by bclaymiles** [comment]
Interesting. I do run antivirus - webroot - which has all sorts of 'live' protective services (on processes, files, etc). I'll try starting up with the AV turned off. Thanks!

**Comment by bclaymiles** [comment]
I tried with just the webroot 'realtime shield' turned off, and it failed again. Then I started with webroot completely disabled - success!
I'll do some more digging, perhaps something during the startup needs to be whitelisted, or if not, i'll contact webroot support about it (they're really responsive, which is great). thanks!

**Comment by bclaymiles** [comment]
Well now I'm totally baffled. I turned webroot back on, and have shut down and restarted Sia  a few times, with no problems at all. ??? If you don't mind, i'm going to leave the ticket open a bit longer just in case, but if it continues running without problem, we'll just chalk it up to ....aliens?

**Comment by bclaymiles** [comment]
Well now I'm totally baffled. I turned webroot back on, and have shut down and restarted Sia  a few times, with no problems at all. ??? If you don't mind, i'm going to leave the ticket open a bit longer just in case, but if it continues running without problem, we'll just chalk it up to ....aliens?

**Comment by bclaymiles** [comment]
No recurrence of issues, even after reboots. I officially attribute it to aliens.

**Comment by lukechampine** [comment]
Very odd. We'll keep an eye out for any new bug reports that resemble this. It looks like https://github.com/NebulousLabs/Sia/pull/2344 may be related.
