### ISSUE TITLE
A critical error loading Sia has occured: Siad unexpectedly exited. Error log

### ISSUE THREAD

**Issue by ghost** [NebulousLabs/Sia-UI#734]
A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
panic: page 39125 already freed

goroutine 22 [running]:
github.com/NebulousLabs/bolt.(*freelist).free(0xc42018e3f0, 0x29920, 0x7feec9479000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/freelist.go:121 +0x29a
github.com/NebulousLabs/bolt.(*node).spill(0xc420c59dc0, 0xc42102b1c0, 0xddf1e0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:363 +0x1e0
github.com/NebulousLabs/bolt.(*node).spill(0xc420c59d50, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xb4
github.com/NebulousLabs/bolt.(*node).spill(0xc420c59ce0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xb4
github.com/NebulousLabs/bolt.(*node).spill(0xc422078690, 0xc42018fb60, 0xc421de2c58)
	/home/luke/go/src/github.com/NebulousLabs/bolt/node.go:350 +0xb4
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc421d40e80, 0xc421de2d00, 0xd)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:570 +0x17b
github.com/NebulousLabs/bolt.(*Bucket).spill(0xc421f720f8, 0x2ca5b7c2, 0xee8be0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:537 +0x8f8
github.com/NebulousLabs/bolt.(*Tx).Commit(0xc421f720e0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/tx.go:163 +0x125
github.com/NebulousLabs/bolt.(*DB).Update(0xc4200fe780, 0xc421de32e8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:610 +0xf7
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedAcceptBlocks(0xc420131b80, 0xc420380000, 0xa, 0xa, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/accept.go:283 +0x519
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedReceiveBlocks(0xc420131b80, 0xde2720, 0xc4214f6080, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:225 +0x5b7
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).(github.com/NebulousLabs/Sia/modules/consensus.managedReceiveBlocks)-fm(0xde2720, 0xc4214f6080, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:445 +0x3e
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedRPC(0xc42007adc0, 0xc420198e20, 0x11, 0xad6ab0, 0xa, 0xc4212ab000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:66 +0x332
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).RPC(0xc42007adc0, 0xc420198e20, 0x11, 0xad6ab0, 0xa, 0xc4212ab000, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/rpc.go:76 +0xd1
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload.func1(0xc420131b80, 0xc421de3ef0, 0xc421de3eb0, 0xc421de3eb8, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:580 +0x12c
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420131b80, 0x0, 0xc420208480)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:601 +0x307
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420204b50, 0xc420131b80, 0xde29a0, 0xc42007adc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a

**Comment by ghost** [comment]
![screenshot from 2017-11-21 16-56-03](https://user-images.githubusercontent.com/31495752/33063453-79bcef4e-cedd-11e7-8888-9eac056cfcfc.png)

**Comment by Selocialadmin** [comment]
![sia error](https://user-images.githubusercontent.com/5036352/33535249-6a6c91ec-d87a-11e7-9fb3-c236fc2f86dc.jpg)
Getting same result saying I need to upgrade but I already had the latest version of Sia UI. Now I'm losing hosting money.

**Comment by tbenz9** [comment]
Duplicate of https://github.com/NebulousLabs/Sia/issues/2413

Recommendation to devs: close
