### ISSUE TITLE
Sia UI will not sync

### ISSUE THREAD

**Issue by Selocialadmin** [NebulousLabs/Sia-UI#736]
I was on the latest Sia UI and for some reason I was given a message I needed to upgrade. I had no choice. When I downloaded the latest 1.3.0 it was the same as I had before. 

Now I cannot sync my wallet and I also have to start the UI with said and I didn't have to do that before. It says not synchronizing. It would say syncing for about 5 seconds and then go back to not synchronizing. 

Now I cannot host and I am afraid I will lost the 13000 coins that my wallet said I was expecting. Please advise. 

Thank you

**Comment by Selocialadmin** [comment]
Now that I have it synced with the blockchain, I have lost all expected coins of 13000 + and had to reset up my 4 terabyte disk. How can I retreave my hosting status I already spent 6 months or more to build up? Highly frustrated right now at whatever fork or update you guys did.

**Comment by tbenz9** [comment]
As long as you have your seed and password your coins are not lost.  I would recommend asking for help in the #help discord channel.  They will be able to give responses faster than through GitHub.  If you have any logs that are showing errors please attach them to this issue.

**Comment by Selocialadmin** [comment]
Hi Thomas,

I had one heading showing the coins i had in my wallet and another heading
showing "expected" coins from my hosting which was 13000+ coins expected.
I also had apprx 250 contracts.  Now that i have synced my wallet and
recovered my wallet with my seed, my coins in my wallet show,  but my
expected coins and contracts  were all gone.   I set up the wallet with the
same path i had mt harddrive before that was hosting and it recignized it
as a new path and the hosting info was not synced.

**Comment by tbenz9** [comment]
Ah, I see.  Check out the various posts about migrating to a new host.  If you don't have a backup of your Sia config you may not be able to recover your contracts.

https://forum.sia.tech/topic/177/moving-to-a-new-server
