### ISSUE TITLE
Sia-UI Issues are killing me!!!

### ISSUE THREAD

**Issue by joycegarcia1** [NebulousLabs/Sia-UI#738]
It worked for me on day one & I was able to deposit my SIA Coins but it looks like it updated automatically and now I get this error every time I open it. What can I do about this????:

A critical error loading Sia has occured: Siad unexpectedly exited. Error log: Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
unexpected fault address 0xd6fe9008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xd6fe9008 pc=0x132d3c9]

goroutine 1 [running]:
runtime.throw(0x16d0af7, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4203ffc38 sp=0xc4203ffc18
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0x1c8 fp=0xc4203ffc88 sp=0xc4203ffc38
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0xd51ee)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:255 +0x69 fp=0xc4203ffd50 sp=0xc4203ffc88
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x3297000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc4203ffde0 sp=0xc4203ffd50
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x149c)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc4203ffea8 sp=0xc4203ffde0
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x33a7000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc4203fff38 sp=0xc4203ffea8
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x15ac)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc420400000 sp=0xc4203fff38
github.com/NebulousLabs/bolt.(*Cursor).searchPage(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x345a000)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:314 +0x156 fp=0xc420400090 sp=0xc420400000
github.com/NebulousLabs/bolt.(*Cursor).search(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x165f)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:271 +0x1bb fp=0xc420400158 sp=0xc420400090
github.com/NebulousLabs/bolt.(*Cursor).seek(0xc420400218, 0xc4204002b8, 0x20, 0x20, 0x0, 0x0, 0x12de7c3, 0xc42010eb78, 0xc4219c3d10, 0x2, ...)
	/home/luke/go/src/github.com/NebulousLabs/bolt/cursor.go:159 +0xb1 fp=0xc4204001a8 sp=0xc420400158
github.com/NebulousLabs/bolt.(*Bucket).Get(0xc4219bec00, 0xc4204002b8, 0x20, 0x20, 0xc4219bec00, 0xfd3136b6686dfebc, 0x5cc6e080d0e02776)
	/home/luke/go/src/github.com/NebulousLabs/bolt/bucket.go:267 +0xef fp=0xc420400248 sp=0xc4204001a8
github.com/NebulousLabs/Sia/modules/consensus.getBlockMap(0xc42010eb60, 0x1f04000000000000, 0xd1a575461055ae1e, 0x9afbf137b0299c39, 0x13b52753e42297a, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusdb.go:185 +0x7d fp=0xc4204002b0 sp=0xc420400248
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc420143b80, 0xc42010eb60, 0x0, 0x0, 0x0, 0xc4219cb440, 0x1, 0x1, 0x0, 0x0, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:53 +0x818 fp=0xc420400eb0 sp=0xc4204002b0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc42010eb60, 0x17081f0, 0xc42010eb60)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:172 +0xe0 fp=0xc420401190 sp=0xc420400eb0
github.com/NebulousLabs/bolt.(*DB).View(0xc420110780, 0xc420095248, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/bolt/db.go:634 +0x9f fp=0xc4204011e0 sp=0xc420401190
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc420143b80, 0x19deca0, 0xc4200751e0, 0xe5f275c545da9b40, 0x4a1de833ab0294a0, 0xb62dcb5a54401d3c, 0x3a57fdd0ea36791d, 0x14d33c7, 0x10e979115)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:180 +0x24f fp=0xc4204012c8 sp=0xc4204011e0
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc420143b80, 0x19deca0, 0xc4200751e0, 0xe5f275c545da9b40, 0x4a1de833ab0294a0, 0xb62dcb5a54401d3c, 0x3a57fdd0ea36791d, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/subscribe.go:203 +0xee fp=0xc420401370 sp=0xc4204012c8
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist(0xc4200751e0, 0xc4200751e0, 0xc4201de870)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:183 +0x944 fp=0xc4204015a8 sp=0xc420401370
github.com/NebulousLabs/Sia/modules/transactionpool.New(0x19ea7c0, 0xc420143b80, 0x19e9ba0, 0xc420074dc0, 0xc42007fb80, 0x46, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/transactionpool.go:101 +0x276 fp=0xc420401620 sp=0xc4204015a8
main.startDaemon(0x0, 0x0, 0x7fff5fbffd1c, 0xe, 0x7fff5fbffd48, 0x5, 0x7fff5fbffd37, 0x5, 0x0, 0x7fff5fbffd9f, ...)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:202 +0x1693 fp=0xc420401bd0 sp=0xc420401620
main.startDaemonCmd(0xc42007d200, 0xc42007f4f0, 0x0, 0x5)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:335 +0x162 fp=0xc420401cd0 sp=0xc420401bd0
github.com/spf13/cobra.(*Command).execute(0xc42007d200, 0xc420054070, 0x5, 0x5, 0xc42007d200, 0xc420054070)
	/home/luke/go/src/github.com/spf13/cobra/command.go:653 +0x299 fp=0xc420401d88 sp=0xc420401cd0
github.com/spf13/cobra.(*Command).ExecuteC(0xc42007d200, 0x16fce88, 0x3b, 0xc420152c80)
	/home/luke/go/src/github.com/spf13/cobra/command.go:728 +0x339 fp=0xc420401ed8 sp=0xc420401d88
github.com/spf13/cobra.(*Command).Execute(0xc42007d200, 0x1aefba0, 0x16e58f7)
	/home/luke/go/src/github.com/spf13/cobra/command.go:687 +0x2b fp=0xc420401f08 sp=0xc420401ed8
main.main()
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/main.go:174 +0x7aa fp=0xc420401f88 sp=0xc420401f08
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc420401fe0 sp=0xc420401f88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420401fe8 sp=0xc420401fe0

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0xff
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 19 [IO wait]:
net.runtime_pollWait(0x1c68130, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420154ca8, 0x72, 0x0, 0xc4211d26a0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420154ca8, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420154c40, 0x0, 0x19dffe0, 0xc4211d26a0)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420064128, 0xc4203e3e70, 0x129d31e, 0x1054480)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420064128, 0x1708860, 0xc420153040, 0x19e6be0, 0xc420012120)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc42009cc60, 0x19e5f20, 0xc420064128, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
main.(*Server).Serve(0xc4200c38c0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/server.go:416 +0x44
main.startDaemon.func1(0xc42015a1e0, 0xc4200c38c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:145 +0x2b
created by main.startDaemon
	/home/luke/go/src/github.com/NebulousLabs/Sia/siad/daemon.go:146 +0x312

goroutine 20 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).threadedSaveLoop(0xc420074dc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/persist.go:57 +0x122
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:249 +0x683

goroutine 21 [IO wait]:
net.runtime_pollWait(0x1c68070, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420154ed8, 0x72, 0x0, 0xc42000a100)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420154ed8, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420154e70, 0x0, 0x19dffe0, 0xc42000a100)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420064158, 0xc400000008, 0xc420014180, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420064158, 0x1708c50, 0xc42015a2a0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:228 +0x49
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentListen(0xc420074dc0, 0xc42015a2a0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:99 +0x75
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:294 +0xa23

goroutine 22 [chan send]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager(0xc420074dc0, 0xc42015a300)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:134 +0x5a8
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:301 +0xacf

goroutine 23 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodeManager(0xc420074dc0, 0xc42015a360)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:283 +0x5e0
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:308 +0xb7b

goroutine 24 [select]:
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentNodePurger(0xc420074dc0, 0xc42015a3c0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/nodes.go:221 +0x650
created by github.com/NebulousLabs/Sia/modules/gateway.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/gateway.go:315 +0xc27

goroutine 5 [IO wait]:
net.runtime_pollWait(0x1c67fb0, 0x77, 0xc4202354c0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42004a0d8, 0x77, 0xc4202354f8, 0x1191899)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitWrite(0xc42004a0d8, 0x1708700, 0x19e6b20)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x34
net.(*netFD).connect(0xc42004a070, 0x19e6b20, 0xc420014400, 0x0, 0x0, 0x19e0220, 0xc42000a180, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:156 +0x24e
net.(*netFD).dial(0xc42004a070, 0x19e6b20, 0xc420014400, 0x19e8a80, 0x0, 0x19e8a80, 0xc4200121e0, 0xc4200416e0, 0x11ad88e)
	/usr/local/go/src/net/sock_posix.go:140 +0xe9
net.socket(0x19e6b20, 0xc420014400, 0x16ced9e, 0x3, 0x2, 0x1, 0x0, 0x0, 0x19e8a80, 0x0, ...)
	/usr/local/go/src/net/sock_posix.go:92 +0x1a1
net.internetSocket(0x19e6b20, 0xc420014400, 0x16ced9e, 0x3, 0x19e8a80, 0x0, 0x19e8a80, 0xc4200121e0, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:154 +0x129
net.doDialTCP(0x19e6b20, 0xc420014400, 0x16ced9e, 0x3, 0x0, 0xc4200121e0, 0x1b0c470, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x19e6b20, 0xc420014400, 0x16ced9e, 0x3, 0x0, 0xc4200121e0, 0xc420014400, 0x40, 0x1)
	/usr/local/go/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x19e6b20, 0xc420014400, 0xc4202a0000, 0x19e33a0, 0xc4200121e0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:521 +0x479
net.dialSerial(0x19e6b20, 0xc420014400, 0xc4202a0000, 0xc42029e520, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:489 +0x220
net.(*Dialer).DialContext(0xc420235c70, 0x19e6b60, 0xc420056398, 0x16ced9e, 0x3, 0xc4201c5e60, 0x12, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:371 +0x70b
net.(*Dialer).Dial(0xc420041c70, 0x16ced9e, 0x3, 0xc4201c5e60, 0x12, 0x10, 0x10, 0x2b56748c8c74562b, 0x10)
	/usr/local/go/src/net/dial.go:294 +0x75
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).dial(0xc420074dc0, 0xc4201c5e60, 0x12, 0x12, 0x1b0d200, 0x400, 0x475)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/conn.go:30 +0xc6
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc420074dc0, 0xc4201c5e60, 0x12, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:498 +0x238
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420074dc0, 0xc4201c5e60, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0x120
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc42000e120, 0xc420074dc0, 0xc4201c5e60, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0x5eb

goroutine 6 [select]:
net.(*Dialer).DialContext.func1(0xc42015a240, 0xc42029e500, 0x19e6b20, 0xc420014400)
	/usr/local/go/src/net/dial.go:331 +0x111
created by net.(*Dialer).DialContext
	/usr/local/go/src/net/dial.go:336 +0xadb

goroutine 7 [select]:
net.(*netFD).connect.func2(0x19e6b20, 0xc420014400, 0xc42004a070, 0xc42000e3c0, 0xc42000e360)
	/usr/local/go/src/net/fd_unix.go:133 +0x1d5
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:144 +0x239

goroutine 27 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/NebulousLabs/Sia/modules/consensus.(*ConsensusSet).threadedInitialBlockchainDownload(0xc420143b80, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/synchronize.go:623 +0x1e2
github.com/NebulousLabs/Sia/modules/consensus.New.func1(0x1, 0xc420298de0, 0xc420143b80, 0x19e9ba0, 0xc420074dc0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:151 +0x3fd
created by github.com/NebulousLabs/Sia/modules/consensus.New
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/consensus/consensusset.go:182 +0x63a

goroutine 28 [select]:
github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).threadedRegularSync(0xc4200751e0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:38 +0x198
created by github.com/NebulousLabs/Sia/modules/transactionpool.(*TransactionPool).initPersist
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/transactionpool/persist.go:126 +0x3ef

goroutine 49 [IO wait]:
net.runtime_pollWait(0x1c67d70, 0x72, 0x18)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42004a1b8, 0x72, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42004a1b8, 0xc4204242d0, 0x8)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42004a150, 0xc4204242d0, 0x8, 0x8, 0x0, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420064078, 0xc4204242d0, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
io.ReadAtLeast(0x111e000e8, 0xc420064078, 0xc4204242d0, 0x8, 0x8, 0x8, 0x15865f7, 0x162cbc0, 0x1587223)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x111e000e8, 0xc420064078, 0xc4204242d0, 0x8, 0x8, 0x8, 0x100c564, 0x1b0c3b0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/NebulousLabs/Sia/encoding.ReadPrefix(0x111e000e8, 0xc420064078, 0x64, 0x100d428, 0x162cbc0, 0x16b2fa0, 0x0, 0x111e000e8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:13 +0x97
github.com/NebulousLabs/Sia/encoding.ReadObject(0x111e000e8, 0xc420064078, 0x15d87c0, 0xc4204242a0, 0x64, 0x0, 0xc420064078)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:28 +0x43
github.com/NebulousLabs/Sia/modules/gateway.connectVersionHandshake(0x19e9620, 0xc420064078, 0x16cfdcd, 0x5, 0xc420064078, 0x0, 0x0, 0x2)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:368 +0x256
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc420074dc0, 0xc4201cc760, 0x11, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:504 +0x288
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420074dc0, 0xc4201cc760, 0x11)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0x120
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc42000e120, 0xc420074dc0, 0xc4201cc760, 0x11)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0x5eb

goroutine 70 [IO wait]:
net.runtime_pollWait(0x1c67cb0, 0x72, 0x19)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420578228, 0x72, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420578228, 0xc420712500, 0x8)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4205781c0, 0xc420712500, 0x8, 0x8, 0x0, 0x19e1ca0, 0x19dc448)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420064088, 0xc420712500, 0x8, 0x8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
io.ReadAtLeast(0x111e000e8, 0xc420064088, 0xc420712500, 0x8, 0x8, 0x8, 0x0, 0x0, 0xc420578228)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x111e000e8, 0xc420064088, 0xc420712500, 0x8, 0x8, 0x8, 0x0, 0xd)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/NebulousLabs/Sia/encoding.ReadPrefix(0x111e000e8, 0xc420064088, 0x64, 0x100d428, 0x162cbc0, 0x16b2fa0, 0x0, 0x111e000e8)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:13 +0x97
github.com/NebulousLabs/Sia/encoding.ReadObject(0x111e000e8, 0xc420064088, 0x15d87c0, 0xc4207124d0, 0x64, 0x0, 0xc420064088)
	/home/luke/go/src/github.com/NebulousLabs/Sia/encoding/prefix.go:28 +0x43
github.com/NebulousLabs/Sia/modules/gateway.connectVersionHandshake(0x19e9620, 0xc420064088, 0x16cfdcd, 0x5, 0xc420064088, 0x0, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:368 +0x256
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedConnect(0xc420074dc0, 0xc4201bf620, 0x12, 0x0, 0x0)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peers.go:504 +0x288
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).managedPeerManagerConnect(0xc420074dc0, 0xc4201bf620, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:13 +0x120
github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager.func1(0xc42000e120, 0xc420074dc0, 0xc4201bf620, 0x12)
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:147 +0xb9
created by github.com/NebulousLabs/Sia/modules/gateway.(*Gateway).permanentPeerManager
	/home/luke/go/src/github.com/NebulousLabs/Sia/modules/gateway/peersmanager.go:148 +0x5eb

**Comment by tbenz9** [comment]
`SIGBUS` indicates that your disk may have errors. Follow these instructions to check for errors:

- [Windows](http://www.thewindowsclub.com/disk-error-checking-windows-8)
- [Mac](https://support.apple.com/en-us/HT201639)
- [Linux](https://www.tecmint.com/check-linux-hard-disk-bad-sectors-bad-blocks/) 

The next version of Sia will present this type of error in a more obvious way instead of crashing with a cryptic error message.

**Comment by joycegarcia1** [comment]
I did and after about 15 minutes it ended with this:

File System check exit code is 0.
Operation Successful.

So what next? Sia-UI still giving me the same exact error....

**Comment by joycegarcia1** [comment]
I should've done my research before transferring my SC to this wallet. It worked the first day then died on me. Apparently (according to thousands of posts on the internet) this is the worse wallet ever. 

Can someone explain to me if and how I can move my SC from this wallet to the paper wallet?

**Comment by tbenz9** [comment]
I'm sorry you're having problems.  I would recommend you ask for help in the Discord server.  They will be able to answer your questions in real time.  If you still have your wallet seed your coins are not lost.

https://discord.gg/sia

If you're not renting or hosting files on Sia I would recommend completely uninstalling and reinstalling Sia.  Then use the 'recover wallet' option to recover your wallet and Siacoin.
