### ISSUE TITLE
Sia-UI unable to fund transaction

### ISSUE THREAD

**Issue by dchirkov** [NebulousLabs/Sia-UI#740]
Hello!
I have last Sia-UI version 1.3.0 and more 200KS on my wallet (see picture). 
When I sent 200KS to other wallet, I got error:

> error when calling /wallet/siacoins: unable to fund transaction: wallet has coins spent in incomplete transactions - not enough remaining coins

Why?

<img width="1167" alt="screen shot 2017-12-13 at 13 05 13" src="https://user-images.githubusercontent.com/633539/33933570-3007a908-e007-11e7-849b-0731f13e4e6c.png">

P.S. I previously created allowance 1200SC, also I sent 10KS - the result is the same

**Comment by tbenz9** [comment]
Duplicate of https://github.com/NebulousLabs/Sia/issues/2443

Devs: Close

**Comment by dchirkov** [comment]
No, it is not duplicate.
I have whole confirmed balance.

**Comment by dchirkov** [comment]
It is error SIA-UI client !

**Comment by tbenz9** [comment]
Once that top transaction listed in your wallet is Confirmed you'll be able to transfer your SC again.  If you still need help please join the Sia Discord a #Help channel.

**Comment by jarcko** [comment]
Still seeing the error
<img width="399" alt="screen shot 2018-01-11 at 11 21 13 am" src="https://user-images.githubusercontent.com/17745048/34817857-cec5d472-f6c1-11e7-92ac-70dc276bb122.png">

**Comment by jjyoung16** [comment]
I'm having the exact same problem.  My wallet shows no unconfirmed transactions and I'm trying to send less than 5% of my current balance.

Edit:  Running version 1.3.2
