### ISSUE TITLE
Not Synchronizing

### ISSUE THREAD

**Issue by nxycdl** [NebulousLabs/Sia-UI#742]
when I run siaui on ubuntu ,but is awalys show me Not synchronizing  0 % , is any cmd can execute ?

**Comment by mschadev** [comment]
Enter terminal and write "gateway connect 185.150.28.28:7781"

**Comment by tbenz9** [comment]
Try following these instructions: https://blog.sia.tech/troubleshooting-the-recent-hardfork-ca77e0b17f0f

Recommendation to devs: close
