### ISSUE TITLE
"Hide OSC Transactions" checkbox active while unlocking wallet

### ISSUE THREAD

**Issue by dlezama** [NebulousLabs/Sia-UI#747]
The checkbox is active when the "Wallet Locked" popup is on top (tested on Windows). If I make the window small enough the checkbox is actually on top of the popup:
![image](https://user-images.githubusercontent.com/28986356/34308493-83f31de8-e702-11e7-9da4-f3ebda5744e4.png)

**Comment by visgotti** [comment]
What is this checkbox for? I don't get a checkbox ever on this prompt and I don't see it in the code anywhere either

**Comment by dlezama** [comment]
As I said it's the "Hide OSC Transactions" from the wallet UI that is active and seen through this dialog.

**Comment by visgotti** [comment]
Ohhh okay I was misunderstanding the problem, sorry. Will look into it.

**Comment by visgotti** [comment]
Where is the Hide OSC Transactions checkbox normally supposed to render?

edit: Okay now that my Sia got transferred into my wallet I see it.

**Comment by visgotti** [comment]
resolved #749
