### ISSUE TITLE
Option to select sia executable and modify config.json when siad isn't found

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#76]

**Comment by DavidVorick** [comment]
Can I extend this? By default it should always use the siad that's packaged with the ui. For me, it'll use the siad in my $PATH by default, which is a problem because I pretty much always have the developer siad in my path.

**Comment by Mingling94** [comment]
Pardon me, I'm jumping back into things after being hella sick after spring break. Where is this siad that's packaged with the UI?

**Comment by DavidVorick** [comment]
resources/default_app/Sia/siad

**Comment by lukechampine** [comment]
(It's not included in the Sia-UI repo, it has to be added manually)

**Comment by Mingling94** [comment]
My approach was rejected by seve :( https://github.com/NebulousLabs/Sia-UI/commit/2517017c304dc270e4bbd0358427645ef08f955b
