### ISSUE TITLE
Cross platform native notifications

### ISSUE THREAD

**Issue by pmknutsen** [NebulousLabs/Sia-UI#77]
Currently, the UI has its own internal notification system. It would be an improvement to instead use native system notifications to report incoming transfers, errors etc. There is a node.js implementation called node-notifier: https://github.com/mikaelbr/node-notifier

**Comment by DavidVorick** [comment]
Feel free to disagree (we're not frontend people), but I think that most of the notifications that get sent through the UI's internal notification system are supposed to stay inside the application, and aren't necessarily important enough to be a system notification.

Another thing to consider is that some setups (IE mine) don't actually have support for system notifications. I think it's a pretty rare situation, but the information should be able to get through even if system notifications are disabled.

We could potentially do both system and in-app notifications. I'm not sure what the best design choices are here.

**Comment by pmknutsen** [comment]
Thinking of it, I agree from a design perspective. Also, dealing with with every OS/desktop may not be realistic. System notifications may be better suited for 3rd party apps built specifically for one particular OS/desktop. I'll go ahead and close this bad idea :)
