### ISSUE TITLE
Set up automated UI testing system

### ISSUE THREAD

**Issue by cyrozap** [NebulousLabs/Sia-UI#78]
We can use something like [zombie](https://www.npmjs.com/package/zombie) to perform a headless test of UI functions. For instance, we can make sure that each tab can be navigated to and that they display the correct information.

**Comment by seveibar** [comment]
I like it! Some user actions get pretty complex e.g. mining, uploading and file, checking if there was an error, so those will be harder and I get concerned the testing suite might get huge (and difficult to maintain!), but maybe that's not such a bad thing.

I think we should definitely start integrating some simple ui tests however, zombie seems like a pretty good framework to do it!

**Comment by cyrozap** [comment]
Bad news: zombie only supports node 0.10, so we'll have to find another testing library.

**Comment by Mingling94** [comment]
For now, since:
- there's so much talk about redoing the UI
- there's not enough manpower for this task
- and this is consequently low priority

I'm closing it for now.
