### ISSUE TITLE
siad and Sia-UI interoperability.

### ISSUE THREAD

**Issue by EvilRedHorse** [NebulousLabs/Sia-UI#804]
If I start siad from the commandline it will use siad's default locations and download a new blockchain, start new wallet, etc...

It should start using the same settings as Sia-UI and you should be able to move between the two applications without losing settings. 

You could then start headless if you wanted and troubleshoot a Sia-UI bug. For example: if the issue was Sia-UI, running just the daemon could bring stability until the Sia-UI bug is fixed.

**Comment by lukechampine** [comment]
Sia-UI is a layer on top of siad, not the other way around. Making siad aware of Sia-UI is out of the question.

You can find Sia-UI's data directory from the About tab. If you run siad in that directory, it will use the Sia-UI blockchain. You can also pass the `-d` flag to siad to specify which data directory to use.
