### ISSUE TITLE
Add package command to bundle Sia-UI with Sia for release

### ISSUE THREAD

**Issue by seveibar** [NebulousLabs/Sia-UI#86]
It's possible that Sia UI should have a separate installer for than the one for Sia UI. @DavidVorick thoughts?

**Comment by DavidVorick** [comment]
I'm not sure what you meant to say.

siad doesn't need an installer, it's just a binary that you run. At this point that is sufficient for us. We might eventually get separate UI's for hosting and mining.

**Comment by seveibar** [comment]
Typo in the original comment- what I meant was should Sia have an installer with a separate UI installer. I think we might need to think about this later but it's not a huge concern ATM.
