### ISSUE TITLE
Install fails on Debian

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia-UI#88]
`npm install && npm start` produces the following error:

```
/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

This seems to be a problem on Debian systems where `nodejs` is used in place of `node`.
The problem can be fixed by symlinking `node` to `nodejs`:
```bash
$ sudo ln -s /usr/bin/nodejs /usr/bin/node
```
Is there any way to fix this automatically?

**Comment by cyrozap** [comment]
`#!/usr/bin/env node` is riddled throughout the dependencies, so the only way to fix it would be to add a note for Debian users to make that symlink to `DEVELOPERS.md`.

**Comment by seveibar** [comment]
It might be possible to add it in the path before running any of those utilities, there may also be a npm package that provides the correct alias.

**Comment by lukechampine** [comment]
Looks like you can also fix it by installing `nodejs-legacy`. I guess it's not really our problem.

**Comment by DavidVorick** [comment]
We should still mention it somewhere in developers.md
