### ISSUE TITLE
Spammed errors about deadlock when starting up

### ISSUE THREAD

**Issue by Mingling94** [NebulousLabs/Sia-UI#90]
![image](https://cloud.githubusercontent.com/assets/4606838/6792932/485f6984-d194-11e4-82e4-ced659b79f5f.png)

Errors of these type keep being sent to terminal, either Windows cmd or Linux, when running Sia-UI

**Comment by lukechampine** [comment]
The errors are coming from siad. We're using a custom mutex that automatically unlocks after a set duration. Our locking scheme isn't perfect yet, which is why you'll sometimes see these errors. They should be relatively harmless though.
