### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia-UI#97]
`/gateway/synchronize` got changed to`/consensus/synchronize`

`/renter/share/save` and `/renter/share/load` got added. These calls save and load '.sia' files, which can be shared to allow other people to download stuff that you have uploaded.

'.sia' files are going to be on the order of a few hundred bytes, maybe we can create them in plaintext? Then people can copy-paste them and share through pastebin or something. There still isn't an easy way to trade small files.

**Comment by cyrozap** [comment]
Would it be possible to have something like a Sia magnet link with the necessary information? Then we could implement a URI handler in the graphical client.

**Comment by DavidVorick** [comment]
actually I just implemented this. The link is unfortunately (after compression) on the order of 2000 characters, but small enough to fit in a clipboard and share over pastebin.

If we were going to create a true Bittorrent style magnet link, we'd need a whole DHT, which is more than we can implement in the next few months.

**Comment by Mingling94** [comment]
@DavidVorick So is this still an issue?

**Comment by DavidVorick** [comment]
:)
